import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { DatabaseSync } from 'node:sqlite';

const SESSION_MS=14*24*60*60*1000;
const now=()=>Date.now();
const token=()=>crypto.randomBytes(32).toString('hex');
function hashPassword(password,salt){return crypto.scryptSync(String(password),salt,64).toString('hex');}
function safeEqual(a,b){try{return crypto.timingSafeEqual(Buffer.from(String(a),'hex'),Buffer.from(String(b),'hex'));}catch{return false;}}
function cleanJson(value,depth=0){
  if(depth>8)return null;
  if(value==null||typeof value==='boolean')return value;
  if(typeof value==='number')return Number.isFinite(value)?Math.max(-1e12,Math.min(1e12,value)):0;
  if(typeof value==='string')return value.slice(0,500);
  if(Array.isArray(value))return value.slice(0,300).map(v=>cleanJson(v,depth+1));
  if(typeof value==='object'){
    const out={};let count=0;
    for(const [k,v] of Object.entries(value)){
      if(++count>250)break;
      if(['__proto__','prototype','constructor'].includes(k))continue;
      out[String(k).slice(0,80)]=cleanJson(v,depth+1);
    }
    return out;
  }
  return null;
}
function cleanSave(raw){const x=cleanJson(raw);if(!x||typeof x!=='object'||Array.isArray(x))throw new Error('잘못된 캐릭터 저장 데이터입니다.');return x;}
function publicUser(row){if(!row)return null;return {id:Number(row.id),username:String(row.username),role:String(row.role||'player'),isDisabled:!!row.is_disabled,createdAt:Number(row.created_at||0),updatedAt:Number(row.updated_at||0)};}

class SqliteWorldStore{
  constructor(filename){fs.mkdirSync(path.dirname(filename),{recursive:true});this.db=new DatabaseSync(filename);this.init();}
  init(){this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS world_users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT NOT NULL UNIQUE COLLATE NOCASE,pass_salt TEXT NOT NULL,pass_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'player',is_disabled INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS world_sessions(token TEXT PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES world_users(id) ON DELETE CASCADE,expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS world_saves(user_id INTEGER PRIMARY KEY REFERENCES world_users(id) ON DELETE CASCADE,payload TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS world_save_backups(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES world_users(id) ON DELETE CASCADE,payload TEXT NOT NULL,revision INTEGER NOT NULL,reason TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS world_audit(id INTEGER PRIMARY KEY AUTOINCREMENT,actor_user_id INTEGER,target_user_id INTEGER NOT NULL,action TEXT NOT NULL,detail TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_world_sessions_user ON world_sessions(user_id);CREATE INDEX IF NOT EXISTS idx_world_backup_user ON world_save_backups(user_id,id DESC);CREATE INDEX IF NOT EXISTS idx_world_audit_target ON world_audit(target_user_id,id DESC);`);this.db.prepare('DELETE FROM world_sessions WHERE expires_at<?').run(now());}
  async register(username,password){const salt=crypto.randomBytes(16).toString('hex'),t=now();try{const r=this.db.prepare('INSERT INTO world_users(username,pass_salt,pass_hash,created_at,updated_at) VALUES(?,?,?,?,?)').run(username,salt,hashPassword(password,salt),t,t);return this.createSession(Number(r.lastInsertRowid));}catch(e){if(String(e).includes('UNIQUE'))throw new Error('이미 사용 중인 준자월드 아이디입니다.');throw e;}}
  async login(username,password){const row=this.db.prepare('SELECT * FROM world_users WHERE username=?').get(username);if(!row||!safeEqual(hashPassword(password,row.pass_salt),row.pass_hash))throw new Error('아이디 또는 비밀번호가 올바르지 않습니다.');if(row.is_disabled)throw new Error('이 준자월드 계정은 이용이 정지되었습니다.');return this.createSession(Number(row.id));}
  createSession(userId){const t=now(),sid=token();this.db.prepare('DELETE FROM world_sessions WHERE user_id=? AND expires_at<?').run(userId,t);this.db.prepare('INSERT INTO world_sessions(token,user_id,expires_at) VALUES(?,?,?)').run(sid,userId,t+SESSION_MS);return {token:sid,user:publicUser(this.db.prepare('SELECT * FROM world_users WHERE id=?').get(userId))};}
  async session(sid){if(!sid)return null;const row=this.db.prepare('SELECT u.* FROM world_sessions s JOIN world_users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>?').get(sid,now());return row&&!row.is_disabled?publicUser(row):null;}
  async logout(sid){if(sid)this.db.prepare('DELETE FROM world_sessions WHERE token=?').run(sid);}
  async getSave(userId){const r=this.db.prepare('SELECT payload,revision,updated_at FROM world_saves WHERE user_id=?').get(userId);if(!r)return {save:null,revision:0,updatedAt:0};return {save:JSON.parse(r.payload),revision:Number(r.revision),updatedAt:Number(r.updated_at)};}
  backup(userId,payload,revision,reason){this.db.prepare('INSERT INTO world_save_backups(user_id,payload,revision,reason,created_at) VALUES(?,?,?,?,?)').run(userId,payload,revision,String(reason).slice(0,80),now());this.db.prepare('DELETE FROM world_save_backups WHERE user_id=? AND id NOT IN (SELECT id FROM world_save_backups WHERE user_id=? ORDER BY id DESC LIMIT 20)').run(userId,userId);}
  audit(actor,target,action,detail=''){this.db.prepare('INSERT INTO world_audit(actor_user_id,target_user_id,action,detail,created_at) VALUES(?,?,?,?,?)').run(actor??null,target,String(action).slice(0,80),String(detail).slice(0,1000),now());}
  async save(userId,raw,expectedRevision=null,reason='autosave'){const save=cleanSave(raw),json=JSON.stringify(save);if(json.length>120000)throw new Error('캐릭터 저장 데이터가 너무 큽니다.');const cur=this.db.prepare('SELECT payload,revision FROM world_saves WHERE user_id=?').get(userId);const rev=Number(cur?.revision||0);if(expectedRevision!=null&&Number(expectedRevision)!==rev)return {conflict:true,...await this.getSave(userId)};if(cur?.payload===json)return {conflict:false,save,revision:rev,updatedAt:now()};if(cur)this.backup(userId,cur.payload,rev,reason);const next=rev+1,t=now();this.db.prepare(`INSERT INTO world_saves(user_id,payload,revision,updated_at) VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET payload=excluded.payload,revision=excluded.revision,updated_at=excluded.updated_at`).run(userId,json,next,t);this.db.prepare('UPDATE world_users SET updated_at=? WHERE id=?').run(t,userId);return {conflict:false,save,revision:next,updatedAt:t};}
  async claimAdmin(userId){this.db.prepare("UPDATE world_users SET role='admin',updated_at=? WHERE id=?").run(now(),userId);this.audit(userId,userId,'admin_claim','JUNJA Land 관리자 인증으로 운영 권한 연결');return publicUser(this.db.prepare('SELECT * FROM world_users WHERE id=?').get(userId));}
  async listUsers(q=''){const like=`%${String(q).trim().slice(0,30)}%`;return this.db.prepare(`SELECT u.id,u.username,u.role,u.is_disabled,u.created_at,u.updated_at,s.payload,s.revision,s.updated_at AS save_updated FROM world_users u LEFT JOIN world_saves s ON s.user_id=u.id WHERE (?='' OR u.username LIKE ? OR s.payload LIKE ?) ORDER BY u.updated_at DESC LIMIT 80`).all(String(q).trim(),like,like).map(r=>{let save=null;try{save=r.payload?JSON.parse(r.payload):null}catch{}return {...publicUser(r),revision:Number(r.revision||0),saveUpdatedAt:Number(r.save_updated||0),character:save?{name:save.name||'',level:Number(save.level||1),heroClass:save.heroClass||'',gold:Number(save.gold||0)}:null};});}
  async adminUser(id){const user=publicUser(this.db.prepare('SELECT * FROM world_users WHERE id=?').get(id));if(!user)return null;const save=await this.getSave(id);return {user,...save};}
  async adminPatch(actor,id,body){const user=this.db.prepare('SELECT * FROM world_users WHERE id=?').get(id);if(!user)throw new Error('사용자를 찾을 수 없습니다.');if(typeof body?.disabled==='boolean'){this.db.prepare('UPDATE world_users SET is_disabled=?,updated_at=? WHERE id=?').run(body.disabled?1:0,now(),id);if(body.disabled)this.db.prepare('DELETE FROM world_sessions WHERE user_id=?').run(id);this.audit(actor,id,body.disabled?'account_disable':'account_enable',body.disabled?'운영자 계정 정지':'운영자 계정 정지 해제');}
    if(body?.savePatch&&typeof body.savePatch==='object'){const current=await this.getSave(id);if(!current.save)throw new Error('아직 생성된 캐릭터가 없습니다.');const patch=cleanSave(body.savePatch),merged={...current.save,...patch};if(patch.resources&&typeof patch.resources==='object')merged.resources={...(current.save.resources||{}),...patch.resources};const result=await this.save(id,merged,null,'admin_edit');this.audit(actor,id,'save_edit',JSON.stringify(patch).slice(0,1000));return {user:publicUser(this.db.prepare('SELECT * FROM world_users WHERE id=?').get(id)),...result};}
    return this.adminUser(id);}
  async backups(id){return this.db.prepare('SELECT id,revision,reason,created_at FROM world_save_backups WHERE user_id=? ORDER BY id DESC LIMIT 20').all(id).map(r=>({id:Number(r.id),revision:Number(r.revision),reason:String(r.reason),createdAt:Number(r.created_at)}));}
  async restore(actor,id,backupId){const b=this.db.prepare('SELECT * FROM world_save_backups WHERE id=? AND user_id=?').get(backupId,id);if(!b)throw new Error('복구할 백업을 찾을 수 없습니다.');const result=await this.save(id,JSON.parse(b.payload),null,'before_restore');this.audit(actor,id,'save_restore',`backup #${backupId} · revision ${b.revision}`);return result;}
  async auditRows(id){return this.db.prepare('SELECT id,actor_user_id,action,detail,created_at FROM world_audit WHERE target_user_id=? ORDER BY id DESC LIMIT 60').all(id).map(r=>({id:Number(r.id),actorUserId:r.actor_user_id==null?null:Number(r.actor_user_id),action:String(r.action),detail:String(r.detail),createdAt:Number(r.created_at)}));}
}

class PostgresWorldStore{
  constructor(pool){this.pool=pool;}
  async init(){await this.pool.query(`CREATE TABLE IF NOT EXISTS world_users(id BIGSERIAL PRIMARY KEY,username TEXT NOT NULL UNIQUE,pass_salt TEXT NOT NULL,pass_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'player',is_disabled BOOLEAN NOT NULL DEFAULT FALSE,created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL);CREATE TABLE IF NOT EXISTS world_sessions(token TEXT PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES world_users(id) ON DELETE CASCADE,expires_at BIGINT NOT NULL);CREATE TABLE IF NOT EXISTS world_saves(user_id BIGINT PRIMARY KEY REFERENCES world_users(id) ON DELETE CASCADE,payload TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,updated_at BIGINT NOT NULL);CREATE TABLE IF NOT EXISTS world_save_backups(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES world_users(id) ON DELETE CASCADE,payload TEXT NOT NULL,revision INTEGER NOT NULL,reason TEXT NOT NULL,created_at BIGINT NOT NULL);CREATE TABLE IF NOT EXISTS world_audit(id BIGSERIAL PRIMARY KEY,actor_user_id BIGINT,target_user_id BIGINT NOT NULL,action TEXT NOT NULL,detail TEXT NOT NULL,created_at BIGINT NOT NULL);CREATE INDEX IF NOT EXISTS idx_world_sessions_user ON world_sessions(user_id);CREATE INDEX IF NOT EXISTS idx_world_backup_user ON world_save_backups(user_id,id DESC);CREATE INDEX IF NOT EXISTS idx_world_audit_target ON world_audit(target_user_id,id DESC);`);await this.pool.query('DELETE FROM world_sessions WHERE expires_at<$1',[now()]);}
  async register(username,password){const salt=crypto.randomBytes(16).toString('hex'),t=now();try{const r=await this.pool.query('INSERT INTO world_users(username,pass_salt,pass_hash,created_at,updated_at) VALUES($1,$2,$3,$4,$5) RETURNING id',[username,salt,hashPassword(password,salt),t,t]);return this.createSession(Number(r.rows[0].id));}catch(e){if(e?.code==='23505')throw new Error('이미 사용 중인 준자월드 아이디입니다.');throw e;}}
  async login(username,password){const r=await this.pool.query('SELECT * FROM world_users WHERE lower(username)=lower($1)',[username]),row=r.rows[0];if(!row||!safeEqual(hashPassword(password,row.pass_salt),row.pass_hash))throw new Error('아이디 또는 비밀번호가 올바르지 않습니다.');if(row.is_disabled)throw new Error('이 준자월드 계정은 이용이 정지되었습니다.');return this.createSession(Number(row.id));}
  async createSession(userId){const sid=token(),t=now();await this.pool.query('DELETE FROM world_sessions WHERE user_id=$1 AND expires_at<$2',[userId,t]);await this.pool.query('INSERT INTO world_sessions(token,user_id,expires_at) VALUES($1,$2,$3)',[sid,userId,t+SESSION_MS]);const u=(await this.pool.query('SELECT * FROM world_users WHERE id=$1',[userId])).rows[0];return {token:sid,user:publicUser(u)};}
  async session(sid){if(!sid)return null;const r=await this.pool.query('SELECT u.* FROM world_sessions s JOIN world_users u ON u.id=s.user_id WHERE s.token=$1 AND s.expires_at>$2',[sid,now()]);const row=r.rows[0];return row&&!row.is_disabled?publicUser(row):null;}
  async logout(sid){if(sid)await this.pool.query('DELETE FROM world_sessions WHERE token=$1',[sid]);}
  async getSave(id){const r=(await this.pool.query('SELECT payload,revision,updated_at FROM world_saves WHERE user_id=$1',[id])).rows[0];if(!r)return {save:null,revision:0,updatedAt:0};return {save:JSON.parse(r.payload),revision:Number(r.revision),updatedAt:Number(r.updated_at)};}
  async backup(id,payload,revision,reason){await this.pool.query('INSERT INTO world_save_backups(user_id,payload,revision,reason,created_at) VALUES($1,$2,$3,$4,$5)',[id,payload,revision,String(reason).slice(0,80),now()]);await this.pool.query('DELETE FROM world_save_backups WHERE user_id=$1 AND id NOT IN (SELECT id FROM world_save_backups WHERE user_id=$1 ORDER BY id DESC LIMIT 20)',[id]);}
  async audit(actor,target,action,detail=''){await this.pool.query('INSERT INTO world_audit(actor_user_id,target_user_id,action,detail,created_at) VALUES($1,$2,$3,$4,$5)',[actor??null,target,String(action).slice(0,80),String(detail).slice(0,1000),now()]);}
  async save(id,raw,expectedRevision=null,reason='autosave'){const save=cleanSave(raw),json=JSON.stringify(save);if(json.length>120000)throw new Error('캐릭터 저장 데이터가 너무 큽니다.');const cur=(await this.pool.query('SELECT payload,revision FROM world_saves WHERE user_id=$1',[id])).rows[0],rev=Number(cur?.revision||0);if(expectedRevision!=null&&Number(expectedRevision)!==rev)return {conflict:true,...await this.getSave(id)};if(cur?.payload===json)return {conflict:false,save,revision:rev,updatedAt:now()};if(cur)await this.backup(id,cur.payload,rev,reason);const next=rev+1,t=now();await this.pool.query('INSERT INTO world_saves(user_id,payload,revision,updated_at) VALUES($1,$2,$3,$4) ON CONFLICT(user_id) DO UPDATE SET payload=EXCLUDED.payload,revision=EXCLUDED.revision,updated_at=EXCLUDED.updated_at',[id,json,next,t]);await this.pool.query('UPDATE world_users SET updated_at=$1 WHERE id=$2',[t,id]);return {conflict:false,save,revision:next,updatedAt:t};}
  async claimAdmin(id){await this.pool.query("UPDATE world_users SET role='admin',updated_at=$1 WHERE id=$2",[now(),id]);await this.audit(id,id,'admin_claim','JUNJA Land 관리자 인증으로 운영 권한 연결');return publicUser((await this.pool.query('SELECT * FROM world_users WHERE id=$1',[id])).rows[0]);}
  async listUsers(q=''){const s=String(q).trim().slice(0,30),like=`%${s}%`;const rows=(await this.pool.query(`SELECT u.id,u.username,u.role,u.is_disabled,u.created_at,u.updated_at,s.payload,s.revision,s.updated_at AS save_updated FROM world_users u LEFT JOIN world_saves s ON s.user_id=u.id WHERE ($1='' OR u.username ILIKE $2 OR COALESCE(s.payload,'') ILIKE $2) ORDER BY u.updated_at DESC LIMIT 80`,[s,like])).rows;return rows.map(r=>{let save=null;try{save=r.payload?JSON.parse(r.payload):null}catch{}return {...publicUser(r),revision:Number(r.revision||0),saveUpdatedAt:Number(r.save_updated||0),character:save?{name:save.name||'',level:Number(save.level||1),heroClass:save.heroClass||'',gold:Number(save.gold||0)}:null};});}
  async adminUser(id){const r=(await this.pool.query('SELECT * FROM world_users WHERE id=$1',[id])).rows[0],user=publicUser(r);if(!user)return null;return {user,...await this.getSave(id)};}
  async adminPatch(actor,id,body){const r=(await this.pool.query('SELECT * FROM world_users WHERE id=$1',[id])).rows[0];if(!r)throw new Error('사용자를 찾을 수 없습니다.');if(typeof body?.disabled==='boolean'){await this.pool.query('UPDATE world_users SET is_disabled=$1,updated_at=$2 WHERE id=$3',[body.disabled,now(),id]);if(body.disabled)await this.pool.query('DELETE FROM world_sessions WHERE user_id=$1',[id]);await this.audit(actor,id,body.disabled?'account_disable':'account_enable',body.disabled?'운영자 계정 정지':'운영자 계정 정지 해제');}
    if(body?.savePatch&&typeof body.savePatch==='object'){const current=await this.getSave(id);if(!current.save)throw new Error('아직 생성된 캐릭터가 없습니다.');const patch=cleanSave(body.savePatch),merged={...current.save,...patch};if(patch.resources&&typeof patch.resources==='object')merged.resources={...(current.save.resources||{}),...patch.resources};const result=await this.save(id,merged,null,'admin_edit');await this.audit(actor,id,'save_edit',JSON.stringify(patch).slice(0,1000));return {user:publicUser((await this.pool.query('SELECT * FROM world_users WHERE id=$1',[id])).rows[0]),...result};}return this.adminUser(id);}
  async backups(id){return (await this.pool.query('SELECT id,revision,reason,created_at FROM world_save_backups WHERE user_id=$1 ORDER BY id DESC LIMIT 20',[id])).rows.map(r=>({id:Number(r.id),revision:Number(r.revision),reason:String(r.reason),createdAt:Number(r.created_at)}));}
  async restore(actor,id,bid){const b=(await this.pool.query('SELECT * FROM world_save_backups WHERE id=$1 AND user_id=$2',[bid,id])).rows[0];if(!b)throw new Error('복구할 백업을 찾을 수 없습니다.');const result=await this.save(id,JSON.parse(b.payload),null,'before_restore');await this.audit(actor,id,'save_restore',`backup #${bid} · revision ${b.revision}`);return result;}
  async auditRows(id){return (await this.pool.query('SELECT id,actor_user_id,action,detail,created_at FROM world_audit WHERE target_user_id=$1 ORDER BY id DESC LIMIT 60',[id])).rows.map(r=>({id:Number(r.id),actorUserId:r.actor_user_id==null?null:Number(r.actor_user_id),action:String(r.action),detail:String(r.detail),createdAt:Number(r.created_at)}));}
}

export async function createWorldStore(root){
  const databaseUrl=String(process.env.DATABASE_URL||'').trim();
  if(databaseUrl){const {Pool}=await import('pg');const pool=new Pool({connectionString:databaseUrl,ssl:/sslmode=require|neon\.tech/i.test(databaseUrl)?{rejectUnauthorized:false}:undefined,max:3});const store=new PostgresWorldStore(pool);await store.init();console.log('[WORLD DB] PostgreSQL persistence enabled.');return store;}
  const store=new SqliteWorldStore(path.join(root,'server-data','junja-world.db'));console.warn('[WORLD DB] DATABASE_URL missing; using local SQLite fallback. Set Neon/Postgres DATABASE_URL for durable production persistence.');return store;
}
