import './v26.css';

const SAVE_KEY='junja-world-v01';
const OWNER_KEY='jw26-save-owner';
type WorldUser={id:number;username:string;role:string;isDisabled:boolean;createdAt:number;updatedAt:number};
let me:WorldUser|null=null;
let revision=0;
let lastSynced='';
let syncBusy=false;
let selectedUserId=0;
let menuOpen=false;

function esc(v:any){return String(v??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]||m));}
function fmt(n:any){return new Intl.NumberFormat('ko-KR').format(Number(n||0));}
function timeText(t:any){const n=Number(t||0);return n?new Intl.DateTimeFormat('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(n)):'-';}
function localRaw(){try{return localStorage.getItem(SAVE_KEY)||''}catch{return ''}}
function localSave(){try{return JSON.parse(localRaw()||'null')}catch{return null}}
function writeLocal(save:any){localStorage.setItem(SAVE_KEY,JSON.stringify(save));}
async function api(url:string,opts:RequestInit={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...opts,headers:{...(opts.body?{'Content-Type':'application/json'}:{}),...(opts.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok){const e:any=new Error(d?.error||'요청에 실패했습니다.');e.status=r.status;e.data=d;throw e;}return d;}
function authStatus(text:string){const el=document.querySelector<HTMLElement>('#jw26-auth-status');if(el)el.textContent=text;}
function syncState(text:string){const el=document.querySelector<HTMLElement>('#jw26-sync-state');if(el)el.textContent=text;}
function gameToast(text:string){const el=document.querySelector<HTMLElement>('#toast');if(!el)return;el.textContent=text;el.classList.remove('hidden');window.setTimeout(()=>el.classList.add('hidden'),2400);}

function createUi(){
 if(!document.querySelector('.jw26-account-gate')){
  const gate=document.createElement('div');gate.className='jw26-account-gate';gate.innerHTML=`<section class="jw26-account-box"><header><small>JUNJA WORLD ACCOUNT</small><h2>준자월드 계정</h2><p>캐릭터를 서버에 저장하고 PC·모바일에서 이어서 플레이</p></header><div class="jw26-tabs"><button class="active" data-jw26-tab="login">로그인</button><button data-jw26-tab="register">회원가입</button></div><form class="jw26-auth-form" id="jw26-auth-form"><label>아이디<input id="jw26-id" maxlength="20" autocomplete="username" placeholder="영문/숫자 3~20자"></label><label>비밀번호<input id="jw26-password" type="password" maxlength="72" autocomplete="current-password" placeholder="6자 이상"></label><button type="submit" id="jw26-auth-submit">준자월드 로그인</button></form><p id="jw26-auth-status" class="jw26-auth-status">계정 상태를 확인하는 중…</p><p class="jw26-auth-note">기존 브라우저 캐릭터가 있다면 첫 로그인 시 서버 계정으로 안전하게 이관합니다. 이후에는 서버 저장이 기준이 됩니다.</p></section>`;document.body.appendChild(gate);
  gate.querySelectorAll<HTMLButtonElement>('[data-jw26-tab]').forEach(b=>b.onclick=()=>setTab(String(b.dataset.jw26Tab||'login')));
  gate.querySelector<HTMLFormElement>('#jw26-auth-form')!.onsubmit=submitAuth;
 }
 const top=document.querySelector<HTMLElement>('.top-bar');
 if(top&&!top.querySelector('.jw26-account-chip')){
  const account=document.createElement('button');account.type='button';account.className='jw26-account-chip';account.innerHTML='<i></i><span>ACCOUNT</span>';account.onclick=toggleMenu;
  const ops=document.createElement('button');ops.type='button';ops.className='jw26-ops-btn';ops.textContent='⚙ 운영';ops.onclick=openOps;
  const anchor=top.querySelector('.jw24-wallet-chip')||top.querySelector('.jw15-guide-button');anchor?.before(account,ops)??top.append(account,ops);
 }
 if(!document.querySelector('.jw26-account-menu')){
  const menu=document.createElement('section');menu.className='jw26-account-menu hidden';menu.innerHTML='<strong id="jw26-menu-user">ACCOUNT</strong><small id="jw26-menu-role">PLAYER</small><div id="jw26-sync-state" class="jw26-sync-state">서버 동기화 준비 중</div><div class="jw26-account-actions"><button id="jw26-claim-admin">관리자 확인</button><button id="jw26-logout">로그아웃</button></div>';document.body.appendChild(menu);
  menu.querySelector<HTMLButtonElement>('#jw26-claim-admin')!.onclick=claimAdmin;
  menu.querySelector<HTMLButtonElement>('#jw26-logout')!.onclick=logout;
 }
 if(!document.querySelector('.jw26-ops-layer')){
  const layer=document.createElement('div');layer.className='jw26-ops-layer hidden';layer.innerHTML=`<section class="jw26-ops-shell"><header class="jw26-ops-head"><div><small>JUNJA WORLD OPERATIONS</small><h3>운영자 콘솔</h3></div><button id="jw26-ops-close">×</button></header><div class="jw26-ops-body"><aside class="jw26-user-side"><div class="jw26-user-search"><input id="jw26-user-query" placeholder="아이디 / 캐릭터 검색"><button id="jw26-user-search-btn">검색</button></div><div id="jw26-user-list" class="jw26-user-list"><div class="jw26-loading">유저 목록 준비 중…</div></div></aside><main id="jw26-user-detail" class="jw26-user-detail"><div class="jw26-empty-detail">왼쪽에서 유저를 선택해.</div></main></div></section>`;document.body.appendChild(layer);
  layer.querySelector<HTMLButtonElement>('#jw26-ops-close')!.onclick=()=>layer.classList.add('hidden');
  layer.querySelector<HTMLButtonElement>('#jw26-user-search-btn')!.onclick=loadUsers;
  layer.querySelector<HTMLInputElement>('#jw26-user-query')!.onkeydown=e=>{if(e.key==='Enter')loadUsers();};
 }
}

let tab:'login'|'register'='login';
function setTab(next:string){tab=next==='register'?'register':'login';document.querySelectorAll<HTMLElement>('[data-jw26-tab]').forEach(b=>b.classList.toggle('active',b.getAttribute('data-jw26-tab')===tab));const btn=document.querySelector<HTMLButtonElement>('#jw26-auth-submit');if(btn)btn.textContent=tab==='login'?'준자월드 로그인':'준자월드 계정 만들기';authStatus(tab==='login'?'서버 캐릭터를 불러옵니다.':'기존 캐릭터가 있으면 이 계정으로 이관됩니다.');}
async function submitAuth(e:SubmitEvent){e.preventDefault();const id=document.querySelector<HTMLInputElement>('#jw26-id'),pw=document.querySelector<HTMLInputElement>('#jw26-password'),btn=document.querySelector<HTMLButtonElement>('#jw26-auth-submit');if(!id||!pw||!btn)return;btn.disabled=true;authStatus(tab==='login'?'로그인 중…':'계정 생성 중…');try{const d=await api(`/api/world/${tab}`,{method:'POST',body:JSON.stringify({username:id.value.trim(),password:pw.value})});pw.value='';me=d.user;await hydrateAccount();}catch(err:any){authStatus(err?.message||'처리에 실패했습니다.');pw.value='';}finally{btn.disabled=false;}}

async function hydrateAccount(){if(!me)return;const server=await api('/api/world/save');revision=Number(server.revision||0);const local=localRaw();if(server.save){const remote=JSON.stringify(server.save);lastSynced=remote;localStorage.setItem(OWNER_KEY,me.username);if(local!==remote){writeLocal(server.save);location.reload();return;}}else if(local){try{const save=JSON.parse(local);const out=await api('/api/world/save',{method:'PUT',body:JSON.stringify({save,revision:0})});revision=Number(out.revision||1);lastSynced=JSON.stringify(out.save||save);}catch(err:any){authStatus(err?.message||'기존 캐릭터 이관에 실패했습니다.');return;}}else{lastSynced='';}
 localStorage.setItem(OWNER_KEY,me.username);showLoggedIn();await maybeAutoClaim();}
function showLoggedIn(){document.querySelector<HTMLElement>('.jw26-account-gate')?.classList.add('hidden');const chip=document.querySelector<HTMLElement>('.jw26-account-chip'),text=chip?.querySelector<HTMLElement>('span'),ops=document.querySelector<HTMLElement>('.jw26-ops-btn');chip?.classList.add('online');if(text&&me)text.textContent=`☁ ${me.username}`;ops?.classList.toggle('show',me?.role==='admin');const u=document.querySelector<HTMLElement>('#jw26-menu-user'),r=document.querySelector<HTMLElement>('#jw26-menu-role'),claim=document.querySelector<HTMLButtonElement>('#jw26-claim-admin');if(u&&me)u.textContent=me.username;if(r&&me)r.textContent=me.role==='admin'?'WORLD ADMIN':'PLAYER';if(claim)claim.style.display=me?.role==='admin'?'none':'block';syncState(`서버 저장 연결 · revision ${revision}`);}
function showLoggedOut(message='준자월드 계정으로 로그인해줘.'){me=null;document.querySelector<HTMLElement>('.jw26-account-gate')?.classList.remove('hidden');document.querySelector<HTMLElement>('.jw26-account-chip')?.classList.remove('online');document.querySelector<HTMLElement>('.jw26-ops-btn')?.classList.remove('show');authStatus(message);}
function toggleMenu(){menuOpen=!menuOpen;document.querySelector<HTMLElement>('.jw26-account-menu')?.classList.toggle('hidden',!menuOpen);}
async function logout(){await syncNow(true);try{await api('/api/world/logout',{method:'POST'})}catch{}localStorage.removeItem(OWNER_KEY);localStorage.removeItem(SAVE_KEY);location.reload();}

async function syncNow(silent=false){if(!me||syncBusy)return;const raw=localRaw();if(!raw||raw===lastSynced)return;syncBusy=true;if(!silent)syncState('서버 저장 중…');try{const save=JSON.parse(raw);const out=await api('/api/world/save',{method:'PUT',body:JSON.stringify({save,revision})});revision=Number(out.revision||revision);lastSynced=JSON.stringify(out.save||save);syncState(`저장 완료 · revision ${revision}`);}catch(err:any){if(err?.status===409&&err?.data?.save){revision=Number(err.data.revision||revision);writeLocal(err.data.save);lastSynced=JSON.stringify(err.data.save);syncState('다른 기기의 최신 저장을 적용합니다…');gameToast('다른 기기의 최신 캐릭터를 불러왔어.');setTimeout(()=>location.reload(),900);}else if(!silent)syncState(err?.message||'서버 저장 실패 · 다시 시도 예정');}finally{syncBusy=false;}}
async function claimAdmin(){if(!me)return;try{syncState('준자랜드 관리자 권한 확인 중…');const d=await api('/api/world/admin/claim',{method:'POST'});me=d.user;showLoggedIn();gameToast('준자월드 운영자 권한이 연결됐어.');}catch(err:any){syncState(err?.message||'관리자 권한을 확인하지 못했습니다.');}}
async function maybeAutoClaim(){if(!me||me.role==='admin')return;try{const w=await api('/api/jcoin/wallet');if(w?.admin)await claimAdmin();}catch{}}

async function openOps(){if(me?.role!=='admin')return;document.querySelector<HTMLElement>('.jw26-ops-layer')?.classList.remove('hidden');await loadUsers();}
async function loadUsers(){if(me?.role!=='admin')return;const q=document.querySelector<HTMLInputElement>('#jw26-user-query')?.value.trim()||'',box=document.querySelector<HTMLElement>('#jw26-user-list');if(!box)return;box.innerHTML='<div class="jw26-loading">유저 목록 불러오는 중…</div>';try{const d=await api('/api/world/admin/users?q='+encodeURIComponent(q));box.innerHTML=(d.users||[]).map((u:any)=>`<button class="jw26-user-card ${u.isDisabled?'disabled':''} ${Number(u.id)===selectedUserId?'selected':''}" data-user-id="${Number(u.id)}"><strong>${esc(u.username)}</strong><span>${u.role==='admin'?'ADMIN':u.isDisabled?'STOP':'USER'}</span><small>${u.character?`${esc(u.character.name)} · Lv.${Number(u.character.level||1)} · ${fmt(u.character.gold)}냥`:'캐릭터 미생성'} · ${timeText(u.saveUpdatedAt||u.updatedAt)}</small></button>`).join('')||'<div class="jw26-loading">검색된 유저가 없어.</div>';box.querySelectorAll<HTMLButtonElement>('[data-user-id]').forEach(b=>b.onclick=()=>loadUser(Number(b.dataset.userId)));}catch(err:any){box.innerHTML=`<div class="jw26-loading">${esc(err?.message||'목록 오류')}</div>`;}}
async function loadUser(id:number){selectedUserId=id;await loadUsers();const detail=document.querySelector<HTMLElement>('#jw26-user-detail');if(!detail)return;detail.innerHTML='<div class="jw26-loading">캐릭터와 로그를 불러오는 중…</div>';try{const [d,b,a]=await Promise.all([api(`/api/world/admin/users/${id}`),api(`/api/world/admin/users/${id}/backups`),api(`/api/world/admin/users/${id}/audit`)]);renderDetail(d,b.backups||[],a.rows||[]);}catch(err:any){detail.innerHTML=`<div class="jw26-loading">${esc(err?.message||'상세 조회 오류')}</div>`;}}
function renderDetail(d:any,backups:any[],logs:any[]){const detail=document.querySelector<HTMLElement>('#jw26-user-detail');if(!detail)return;const u=d.user,s=d.save||{};detail.innerHTML=`<div class="jw26-detail-title"><div><h4>${esc(u.username)} ${s.name?`· ${esc(s.name)}`:''}</h4><p>ID ${Number(u.id)} · 저장 revision ${Number(d.revision||0)} · ${timeText(d.updatedAt)}</p></div><span class="jw26-state-badge ${u.isDisabled?'disabled':''}">${u.isDisabled?'이용 정지':'정상 이용'}</span></div><div class="jw26-admin-note">운영자 콘솔은 준자월드 캐릭터/엽전/아이템/계정만 관리해. <b>J-Coin 지급·차감·전송은 여기서 할 수 없어.</b></div>${d.save?`<div class="jw26-edit-grid"><label>레벨<input id="jw26-e-level" type="number" min="1" max="999" value="${Number(s.level||1)}"></label><label>엽전<input id="jw26-e-gold" type="number" min="0" value="${Number(s.gold||0)}"></label><label>회복약<input id="jw26-e-potions" type="number" min="0" value="${Number(s.potions||0)}"></label><label>무기 +<input id="jw26-e-weapon" type="number" min="0" max="99" value="${Number(s.weaponLevel||0)}"></label><label>방어구 +<input id="jw26-e-armor" type="number" min="0" max="99" value="${Number(s.armorLevel||0)}"></label></div>`:'<div class="jw26-admin-note">아직 이 계정에는 캐릭터가 생성되지 않았어.</div>'}<div class="jw26-op-actions">${d.save?'<button class="primary" id="jw26-save-user">캐릭터 수정 적용</button>':''}<button class="danger" id="jw26-toggle-user">${u.isDisabled?'계정 정지 해제':'계정 이용 정지'}</button><button id="jw26-refresh-user">새로고침</button></div><div class="jw26-detail-columns"><section class="jw26-log-box"><h5>저장 백업 · 최대 20개</h5><div class="jw26-log-list">${backups.map((x:any)=>`<div class="jw26-log-row"><b>rev ${Number(x.revision)}</b> · ${esc(x.reason)}<button data-backup-id="${Number(x.id)}">복구</button><br>${timeText(x.createdAt)}</div>`).join('')||'<div class="jw26-log-row">아직 백업이 없어.</div>'}</div></section><section class="jw26-log-box"><h5>운영 로그</h5><div class="jw26-log-list">${logs.map((x:any)=>`<div class="jw26-log-row"><b>${esc(x.action)}</b><br>${esc(x.detail)}<br>${timeText(x.createdAt)}</div>`).join('')||'<div class="jw26-log-row">운영 기록이 없어.</div>'}</div></section></div>`;
 detail.querySelector<HTMLButtonElement>('#jw26-refresh-user')!.onclick=()=>loadUser(Number(u.id));
 const toggle=detail.querySelector<HTMLButtonElement>('#jw26-toggle-user');if(toggle)toggle.onclick=()=>toggleUser(Number(u.id),!u.isDisabled);
 const saveBtn=detail.querySelector<HTMLButtonElement>('#jw26-save-user');if(saveBtn)saveBtn.onclick=()=>applyUserSave(Number(u.id));
 detail.querySelectorAll<HTMLButtonElement>('[data-backup-id]').forEach(b=>b.onclick=()=>restoreUser(Number(u.id),Number(b.dataset.backupId)));
}
async function toggleUser(id:number,disabled:boolean){if(!confirm(disabled?'이 계정을 즉시 정지할까? 현재 로그인 세션도 종료돼.':'이 계정의 정지를 해제할까?'))return;try{await api(`/api/world/admin/users/${id}`,{method:'PATCH',body:JSON.stringify({disabled})});await loadUser(id);await loadUsers();}catch(err:any){gameToast(err?.message||'계정 상태 변경 실패');}}
function numberValue(id:string,min=0,max=1e9){const n=Math.trunc(Number(document.querySelector<HTMLInputElement>(id)?.value||0));return Math.max(min,Math.min(max,Number.isFinite(n)?n:min));}
async function applyUserSave(id:number){const patch={level:numberValue('#jw26-e-level',1,999),gold:numberValue('#jw26-e-gold',0,1e12),potions:numberValue('#jw26-e-potions',0,1e6),weaponLevel:numberValue('#jw26-e-weapon',0,99),armorLevel:numberValue('#jw26-e-armor',0,99)};if(!confirm(`Lv.${patch.level} · ${fmt(patch.gold)}냥으로 저장할까?`))return;try{await api(`/api/world/admin/users/${id}`,{method:'PATCH',body:JSON.stringify({savePatch:patch})});await loadUser(id);await loadUsers();}catch(err:any){gameToast(err?.message||'캐릭터 수정 실패');}}
async function restoreUser(id:number,backupId:number){if(!confirm(`백업 #${backupId} 상태로 캐릭터를 복구할까? 현재 상태도 먼저 백업돼.`))return;try{await api(`/api/world/admin/users/${id}/restore`,{method:'POST',body:JSON.stringify({backupId})});await loadUser(id);await loadUsers();}catch(err:any){gameToast(err?.message||'복구 실패');}}

async function boot(){createUi();const owner=localStorage.getItem(OWNER_KEY);try{const d=await api('/api/world/me');me=d.user;await hydrateAccount();}catch{if(owner){localStorage.removeItem(OWNER_KEY);localStorage.removeItem(SAVE_KEY);}showLoggedOut('준자월드 계정으로 로그인해줘.');}
 window.setInterval(()=>syncNow(true),3500);window.setInterval(()=>{if(me?.role!=='admin')maybeAutoClaim();},15000);window.addEventListener('beforeunload',()=>{if(me&&localRaw()&&localRaw()!==lastSynced){fetch('/api/world/save',{method:'PUT',credentials:'same-origin',keepalive:true,headers:{'Content-Type':'application/json'},body:JSON.stringify({save:localSave(),revision})}).catch(()=>{});}});window.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector<HTMLElement>('.jw26-account-menu')?.classList.add('hidden');menuOpen=false;document.querySelector<HTMLElement>('.jw26-ops-layer')?.classList.add('hidden');}});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
