import Phaser from 'phaser';
import './v21.css';

type Hero='warrior'|'mage'|'ranger';
type State={charge:number;lastProc:number;patched:boolean};
const states=new WeakMap<any,State>();
const trackedGames=new Set<any>();

function installTracking(){const proto=(Phaser.Game as any)?.prototype;if(!proto||proto.__jwV21Tracked)return;const boot=proto.boot,destroy=proto.destroy;if(typeof boot==='function')proto.boot=function(...args:any[]){trackedGames.add(this);return boot.apply(this,args);};if(typeof destroy==='function')proto.destroy=function(...args:any[]){trackedGames.delete(this);return destroy.apply(this,args);};proto.__jwV21Tracked=true;}
installTracking();
function scene():any|null{const games=[...trackedGames,...((((Phaser as any).GAMES||[]) as any[]))];for(const game of games){const direct=game?.scene?.keys?.world;if(direct?.sys?.isActive?.())return direct;try{const s=game?.scene?.getScene?.('world');if(s?.sys?.isActive?.())return s;}catch{}}return null;}
function hero(s:any):Hero{return (s?.save?.heroClass||'warrior') as Hero;}
function alive(m:any){return !!m&&m.active!==false&&m.visible!==false&&!m.destroyed&&Number(m.getData?.('hp')||0)>0;}
function power(s:any){const h=hero(s),base=h==='mage'?31:h==='ranger'?27:24;return base+Math.max(0,Number(s?.save?.level||1)-1)*5+Number(s?.save?.weaponLevel||0)*5;}
function enemies(s:any,radius:number){if(!s?.player)return[];return (s?.monsters?.getChildren?.()||[]).filter((m:any)=>alive(m)&&Phaser.Math.Distance.Between(s.player.x,s.player.y,m.x,m.y)<=radius).sort((a:any,b:any)=>Phaser.Math.Distance.Between(s.player.x,s.player.y,a.x,a.y)-Phaser.Math.Distance.Between(s.player.x,s.player.y,b.x,b.y));}
function hit(s:any,m:any,damage:number,color:number){if(!alive(m))return;const hp=Number(m.getData?.('hp')||0)-damage;m.setData?.('hp',hp);try{m.setTintFill?.(0xffffff);s.time.delayedCall(70,()=>m?.clearTint?.());const t=s.add.text(m.x,m.y-54,`-${damage}`,{fontFamily:'Noto Sans KR',fontSize:'15px',fontStyle:'bold',color:`#${color.toString(16).padStart(6,'0')}`,stroke:'#101820',strokeThickness:4}).setOrigin(.5).setDepth(m.y+130);s.tweens.add({targets:t,y:t.y-30,alpha:0,duration:460,onComplete:()=>t.destroy()});}catch{}if(hp<=0){try{s.defeat?.(m);}catch{}}}
function procFx(s:any,h:Hero){const p=s.player;if(!p)return;const color=h==='warrior'?0xffc85d:h==='mage'?0x74dcff:0xb7ef73;const ring=s.add.circle(p.x,p.y,30,color,.08).setStrokeStyle(5,color,.95).setDepth(p.y+125);s.tweens.add({targets:ring,scale:3.1,alpha:0,duration:360,ease:'Cubic.out',onComplete:()=>ring.destroy()});for(let i=0;i<8;i++){const a=Math.PI*2*i/8;const dot=s.add.circle(p.x,p.y,3,color,.95).setDepth(p.y+128);s.tweens.add({targets:dot,x:p.x+Math.cos(a)*75,y:p.y+Math.sin(a)*48,alpha:0,duration:320,onComplete:()=>dot.destroy()});}}
function triggerPassive(s:any,state:State){const h=hero(s),list=enemies(s,h==='ranger'?390:190);if(!list.length)return;const base=power(s);procFx(s,h);if(h==='warrior'){const dmg=Math.max(1,Math.round(base*.48));list.slice(0,3).forEach((m:any)=>hit(s,m,dmg,0xffd77a));toast('검객 · 검기폭발','주변 적에게 추가 참격');}else if(h==='mage'){const dmg=Math.max(1,Math.round(base*.42));list.slice(0,3).forEach((m:any,i:number)=>s.time.delayedCall(i*65,()=>hit(s,m,dmg,0x9cecff)));toast('도사 · 영력연쇄','영력이 가까운 적에게 연쇄');}else{const dmg=Math.max(1,Math.round(base*.56));const target=list[0];const line=s.add.line(0,0,s.player.x,s.player.y,target.x,target.y,0xd8ff9c,.95).setOrigin(0).setLineWidth(5).setDepth(Math.max(s.player.y,target.y)+130);s.tweens.add({targets:line,alpha:0,duration:180,onComplete:()=>line.destroy()});hit(s,target,dmg,0xc9ff96);toast('궁사 · 집중사격','가장 가까운 적에게 추가 관통사격');}try{s.cameras?.main?.shake?.(80,.0022);}catch{}state.lastProc=performance.now();}
function patch(s:any){let st=states.get(s);if(!st){st={charge:0,lastProc:0,patched:false};states.set(s,st);}if(st.patched||typeof s.attack!=='function')return;const original=s.attack.bind(s);s.attack=function(...args:any[]){const result=original(...args);if(String(s.zone||'village')!=='village'){st!.charge=Math.min(3,st!.charge+1);if(st!.charge>=3&&performance.now()-st!.lastProc>650){st!.charge=0;s.time?.delayedCall?.(70,()=>triggerPassive(s,st!));}render(s,st!);}return result;};st.patched=true;}
function createUi(){if(document.querySelector('.jw21-class-meter'))return;const el=document.createElement('div');el.className='jw21-class-meter';el.innerHTML='<div class="jw21-head"><b id="jw21-name">직업 특성</b><span id="jw21-passive">PASSIVE</span></div><div class="jw21-pips"><i></i><i></i><i></i></div><small id="jw21-desc"></small>';document.body.appendChild(el);}
function render(s:any,st:State){createUi();const el=document.querySelector<HTMLElement>('.jw21-class-meter'),name=document.querySelector<HTMLElement>('#jw21-name'),passive=document.querySelector<HTMLElement>('#jw21-passive'),desc=document.querySelector<HTMLElement>('#jw21-desc');if(!el||!name||!passive||!desc)return;const h=hero(s);el.className=`jw21-class-meter ${h} ${String(s.zone)==='village'?'is-village':''}`;name.textContent=h==='warrior'?'검객 · 검기':h==='mage'?'도사 · 영력':'궁사 · 집중';passive.textContent=h==='warrior'?'검기폭발':h==='mage'?'영력연쇄':'집중사격';desc.textContent=h==='warrior'?'기본 공격 3회마다 주변 추가 참격':h==='mage'?'기본 공격 3회마다 연쇄 영력 피해':'기본 공격 3회마다 추가 관통사격';el.querySelectorAll<HTMLElement>('.jw21-pips i').forEach((p,i)=>p.classList.toggle('on',i<st.charge));}
function toast(title:string,body:string){let el=document.querySelector<HTMLElement>('.jw21-proc-toast');if(!el){el=document.createElement('div');el.className='jw21-proc-toast';document.body.appendChild(el);}el.innerHTML=`<b>${title}</b><small>${body}</small>`;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');window.setTimeout(()=>el?.classList.remove('show'),1100);}
function tick(){const s=scene();if(!s?.player)return;patch(s);const st=states.get(s);if(st)render(s,st);}
function boot(){createUi();window.setInterval(tick,160);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
