import Phaser from 'phaser';
import './v14.css';

const SAVE_KEY='junja-world-v01';
const trackedGames=new Set<any>();
const patchedScenes=new WeakSet<any>();
const sceneMeta=new WeakMap<any,{travel?:(zone:any)=>void}>();
let dungeonActive=false;
let dungeonKills=0;
let dungeonBossSpawned=false;
let dungeonScene:any=null;
let dungeonLabels:any[]=[];
let lastUiRender=0;

type Chapter4={state:number;kills:number;bossDone:boolean;rewarded:boolean};
type Talents={mastery:number;guard:number;fortune:number};

function installTracking(){const proto=(Phaser.Game as any)?.prototype;if(!proto||proto.__jwV14Tracked)return;const boot=proto.boot,destroy=proto.destroy;if(typeof boot==='function')proto.boot=function(...args:any[]){trackedGames.add(this);return boot.apply(this,args);};if(typeof destroy==='function')proto.destroy=function(...args:any[]){trackedGames.delete(this);return destroy.apply(this,args);};proto.__jwV14Tracked=true;}
installTracking();
function scene():any|null{const games=[...trackedGames,...((((Phaser as any).GAMES||[]) as any[]))];for(const game of games){const direct=game?.scene?.keys?.world;if(direct?.sys?.isActive?.())return direct;try{const s=game?.scene?.getScene?.('world');if(s?.sys?.isActive?.())return s;}catch{}}return null;}
function readSave():any{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null');}catch{return null;}}
function writeSave(save:any,s?:any){localStorage.setItem(SAVE_KEY,JSON.stringify(save));if(s?.save)Object.assign(s.save,save);}
function toast(msg:string){const el=document.querySelector<HTMLElement>('#toast');if(!el)return;el.textContent=msg;el.classList.remove('hidden');window.setTimeout(()=>el.classList.add('hidden'),2400);}
function chapter3Done(save:any){return Number(save?.chapter3?.state||0)>=5;}
function ensureChapter4(save:any):Chapter4{if(!save.chapter4||typeof save.chapter4!=='object')save.chapter4={state:0,kills:0,bossDone:false,rewarded:false};save.chapter4.state=Number(save.chapter4.state||0);save.chapter4.kills=Number(save.chapter4.kills||0);save.chapter4.bossDone=!!save.chapter4.bossDone;save.chapter4.rewarded=!!save.chapter4.rewarded;return save.chapter4 as Chapter4;}
function ensureTalents(save:any):Talents{if(!save.jw14Talents||typeof save.jw14Talents!=='object')save.jw14Talents={mastery:0,guard:0,fortune:0};for(const k of ['mastery','guard','fortune'] as const)save.jw14Talents[k]=Math.max(0,Math.min(3,Number(save.jw14Talents[k]||0)));return save.jw14Talents as Talents;}
function cores(save:any){save.jw14SealCores=Math.max(0,Number(save.jw14SealCores||0));return Number(save.jw14SealCores);}
function clears(save:any){save.jw14DungeonClears=Math.max(0,Number(save.jw14DungeonClears||0));return Number(save.jw14DungeonClears);}
function shards(save:any){save.jw13Shards=Math.max(0,Number(save.jw13Shards||0));return Number(save.jw13Shards);}
function level(save:any){return Math.max(1,Number(save?.level||1));}
function totalTalentPoints(save:any){return Math.max(0,Math.floor((level(save)-5)/3))+Math.min(5,clears(save));}
function spentTalentPoints(save:any){const t=ensureTalents(save);return t.mastery+t.guard+t.fortune;}
function availableTalentPoints(save:any){return Math.max(0,totalTalentPoints(save)-spentTalentPoints(save));}
function maxHpFromHud(){const text=document.querySelector<HTMLElement>('#hp-text')?.textContent||'';const max=Number(text.split('/')[1]?.trim()||0);return max>0?max:999999;}
function refreshHp(save:any){const max=maxHpFromHud(),hp=Math.max(0,Math.min(max,Number(save.hp||0)));const text=document.querySelector<HTMLElement>('#hp-text'),bar=document.querySelector<HTMLElement>('#hp-bar');if(text)text.textContent=`${Math.round(hp)} / ${Math.round(max)}`;if(bar)bar.style.width=`${Math.max(0,Math.min(100,hp/max*100))}%`;}
function stopAuto(){const b=document.querySelector<HTMLButtonElement>('#jw-auto-hunt');if(b?.classList.contains('on'))b.click();}

function createUi(){
 if(!document.querySelector('.jw14-dungeon-fx')){const fx=document.createElement('div');fx.className='jw14-dungeon-fx';document.body.appendChild(fx);}
 if(!document.querySelector('.jw14-dungeon-hud')){const hud=document.createElement('div');hud.className='jw14-dungeon-hud';hud.innerHTML='<b>봉인동굴</b><small>봉인수하 토벌 준비중</small>';document.body.appendChild(hud);}
 if(!document.querySelector('.jw14-quest-button')){const b=document.createElement('button');b.className='jw14-quest-button hidden';b.type='button';b.innerHTML='<b>4장 · 준비 중</b><small>메인 임무 3장 완료 후 개방</small>';b.addEventListener('click',questAction);document.body.appendChild(b);}
 const dock=document.querySelector('.zone-dock');if(dock&&!dock.querySelector('.jw14-dungeon-button')){const b=document.createElement('button');b.className='jw14-dungeon-button locked';b.type='button';b.textContent='봉인동굴 Lv.15';b.addEventListener('click',()=>enterDungeon());dock.appendChild(b);}
 if(!document.querySelector('.jw14-dungeon-clear')){const layer=document.createElement('section');layer.className='jw14-dungeon-clear hidden';layer.innerHTML='<div class="jw14-clear-card"><div class="crest">封</div><h2>봉인동굴 정화 완료</h2><p>봉인의 핵을 회수했습니다. 반복 정화로 세트 축복을 해금할 수 있습니다.</p><div class="jw14-reward-grid"><div><b>+1</b>봉인의 핵</div><div><b>+6</b>장비 파편</div><div><b>+1,500</b>엽전</div></div><div class="jw14-clear-actions"><button data-jw14-return>백운성 귀환</button><button data-jw14-retry>던전 재도전</button></div></div>';layer.querySelector<HTMLButtonElement>('[data-jw14-return]')!.onclick=()=>{layer.classList.add('hidden');leaveDungeon('village');};layer.querySelector<HTMLButtonElement>('[data-jw14-retry]')!.onclick=()=>{layer.classList.add('hidden');restartDungeon();};document.body.appendChild(layer);}
}

function ensureGrowthBoxes(){const inv=document.querySelector<HTMLElement>('#inventory-panel');if(!inv)return;if(!inv.querySelector('.jw14-skill-box')){const box=document.createElement('section');box.className='jw14-skill-box';box.innerHTML='<div class="jw14-box-head"><b>직업 성장 · 특성</b><span>포인트 0</span></div><div class="jw14-skill-grid"></div>';const anchor=inv.querySelector('.jw-reforge-box')||inv.querySelector('.jw-inventory-overview')||inv.querySelector('#equip-text');anchor?.insertAdjacentElement('afterend',box)??inv.appendChild(box);}if(!inv.querySelector('.jw14-set-box')){const box=document.createElement('section');box.className='jw14-set-box';const skill=inv.querySelector('.jw14-skill-box');(skill||inv).insertAdjacentElement?.('afterend',box);if(!box.parentElement)inv.appendChild(box);}}
function talentNames(save:any){const hero=String(save?.heroClass||'warrior');return hero==='mage'?['월령 숙련','호신 결계','영맥 탐지']:hero==='ranger'?['추적 숙련','회피 호흡','전리품 감각']:['혈전 숙련','강철 심장','전리품 감각'];}
function renderGrowth(){ensureGrowthBoxes();const save=readSave();if(!save)return;const t=ensureTalents(save),names=talentNames(save),left=availableTalentPoints(save),skill=document.querySelector<HTMLElement>('.jw14-skill-box'),set=document.querySelector<HTMLElement>('.jw14-set-box');if(skill){const head=skill.querySelector<HTMLElement>('.jw14-box-head span');if(head)head.textContent=`포인트 ${left}`;const grid=skill.querySelector<HTMLElement>('.jw14-skill-grid');if(grid){const rows:[keyof Talents,string,string][]=[['mastery',names[0],'처치 시 회복 +1% / 보상 엽전 +4%'],['guard',names[1],'받는 피해 완화 +5%'],['fortune',names[2],'처치 시 장비 파편 추가 획득 확률 +8%']];grid.innerHTML=rows.map(([key,name,desc])=>`<button class="jw14-talent ${t[key]>=3?'max':''}" data-jw14-talent="${key}" ${left<=0||t[key]>=3?'disabled':''}><b>${name}</b><small>${desc}</small><em>단계 ${t[key]} / 3</em></button>`).join('');grid.querySelectorAll<HTMLButtonElement>('[data-jw14-talent]').forEach(b=>b.onclick=()=>upgradeTalent(b.dataset.jw14Talent as keyof Talents));}}if(set){const c=cores(save);set.innerHTML=`<div class="jw14-box-head"><b>봉인수호 세트 축복</b><span>봉인의 핵 ${c}</span></div>${setTier(1,c,'Ⅰ','정화의 금빛','처치 엽전 +5%')}${setTier(3,c,'Ⅱ','수호의 결계','받는 피해 8% 완화')}${setTier(6,c,'Ⅲ','월영 재생','처치 시 최대 HP 3% 회복')}<div class="jw14-set-progress"><i style="width:${Math.min(100,c/6*100)}%"></i></div>`;}}
function setTier(req:number,count:number,icon:string,name:string,effect:string){return `<div class="jw14-set-tier ${count>=req?'active':''}"><i>${icon}</i><div><b>${name}</b>${effect}</div><span>${count>=req?'활성':'핵 '+req+'개'}</span></div>`;}
function upgradeTalent(key:keyof Talents){const s=scene(),save=s?.save||readSave();if(!save)return;const t=ensureTalents(save);if(t[key]>=3){toast('이미 최고 단계입니다.');return;}if(availableTalentPoints(save)<1){toast('사용 가능한 특성 포인트가 없습니다.');return;}t[key]++;writeSave(save,s);toast('특성 강화 완료');renderGrowth();}

function renderQuest(){const save=readSave(),b=document.querySelector<HTMLButtonElement>('.jw14-quest-button'),d=document.querySelector<HTMLButtonElement>('.jw14-dungeon-button');if(!save||!b||!d)return;const unlocked=chapter3Done(save);b.classList.toggle('hidden',!unlocked);const lv=level(save),ch=ensureChapter4(save);d.classList.toggle('locked',!unlocked||lv<15||ch.state===0);d.classList.toggle('active',dungeonActive);if(!unlocked)return;if(lv<15){b.className='jw14-quest-button';b.innerHTML=`<b>4장 · Lv.15 필요</b><small>현재 Lv.${lv} · 월영숲과 정예 토벌로 성장하세요.</small>`;return;}let title='',sub='';b.classList.remove('complete','ready');if(ch.state===0){title='4장 · 백운의 밀명';sub='촌장 백운에게 봉인동굴의 이상 징후를 보고받자.';b.classList.add('ready');}else if(ch.state===1){title='4장 · 봉인동굴 진입';sub='봉인동굴에 입장해 봉인수하를 추적하자.';}else if(ch.state===2){title=`4장 · 봉인수하 토벌 ${Math.min(ch.kills,12)}/12`;sub='자동사냥 사용 가능 · 12마리 처치 후 수호자 출현';}else if(ch.state===3){title='4장 · 봉인파괴자';sub='동굴 심층의 봉인파괴자를 격파하자.';b.classList.add('ready');}else if(ch.state===4){title='4장 · 봉인의 핵';sub='백운성으로 돌아가 촌장 백운에게 결과를 보고하자.';b.classList.add('ready');}else{title='4장 완료 · 봉인동굴';sub=`정화 ${clears(save)}회 · 반복 정화로 봉인수호 세트를 성장시키세요.`;b.classList.add('complete');}b.innerHTML=`<b>${title}</b><small>${sub}</small>`;}
function questAction(){const s=scene(),save=s?.save||readSave();if(!save||!chapter3Done(save))return;if(level(save)<15){toast('메인 임무 4장은 Lv.15부터 시작할 수 있습니다.');return;}const ch=ensureChapter4(save);if(ch.state===0||ch.state===4){stopAuto();if(dungeonActive)leaveDungeon();const meta=s?sceneMeta.get(s):undefined;meta?.travel?.('village');window.setTimeout(()=>{if(s?.player)s.autoTarget=new Phaser.Math.Vector2(1070,720);},160);toast('촌장 백운에게 자동이동합니다.');}else enterDungeon();}

function destroyDungeonLabels(){for(const obj of dungeonLabels)try{obj?.destroy?.();}catch{}dungeonLabels=[];}
function attachLabel(s:any,m:any,name:string,boss=false){try{const text=s.add.text(m.x,m.y-(boss?82:50),name,{fontFamily:'Noto Sans KR',fontSize:boss?'12px':'9px',fontStyle:'bold',color:boss?'#ffe09b':'#e5d9ef',stroke:'#17131e',strokeThickness:4}).setOrigin(.5).setDepth(5000);const bg=s.add.rectangle(m.x,m.y-(boss?64:36),boss?112:72,4,0x14121a,.9).setOrigin(.5).setDepth(4998);const fill=s.add.rectangle(m.x-(boss?56:36),m.y-(boss?64:36),boss?112:72,4,boss?0xd7a04d:0x8b65b3,1).setOrigin(0,.5).setDepth(4999);m.setData('jw14Label',{text,bg,fill,boss});dungeonLabels.push(text,bg,fill);}catch{}}
function updateLabels(s:any){for(const m of s?.monsters?.getChildren?.()||[]){const ui=m?.getData?.('jw14Label');if(!ui)continue;const show=!!m.active;ui.text?.setVisible?.(show);ui.bg?.setVisible?.(show);ui.fill?.setVisible?.(show);if(!show)continue;const off=ui.boss?82:50,bar=ui.boss?64:36,width=ui.boss?112:72,max=Math.max(1,Number(m.getData('maxHp')||1)),hp=Math.max(0,Number(m.getData('hp')||0));ui.text.setPosition(m.x,m.y-off);ui.bg.setPosition(m.x,m.y-bar);ui.fill.setPosition(m.x-width/2,m.y-bar).setDisplaySize(width*Math.min(1,hp/max),4);}}
function spawnDungeonMobs(s:any){const names=['봉인수하','균열망령','동굴마귀'];for(let i=0;i<14;i++){const x=360+(i%4)*500+Phaser.Math.Between(-55,55),y=300+Math.floor(i/4)*330+Phaser.Math.Between(-45,45),hp=230+i*11,damage=19+Math.floor(i/4)*2,xp=92,gold=62;const m=s.monsters.create(x,y,'slime');m.setScale(.135).setTint(i%3===0?0x987ac4:i%3===1?0xb0a0c5:0x77618f).setSize(260,180).setOffset(120,300).setData({name:names[i%names.length],hp,maxHp:hp,damage,xp,gold,bornX:x,bornY:y,nextMove:0,isBoss:false,jw14DungeonMob:true,jw14Counted:false});try{m.play('slime-idle');}catch{}attachLabel(s,m,names[i%names.length]);}}
function spawnDungeonBoss(s:any){if(!dungeonActive||dungeonBossSpawned)return;dungeonBossSpawned=true;for(const m of s.monsters?.getChildren?.()||[])if(m?.getData?.('jw14DungeonMob'))try{m.disableBody(true,true);}catch{}const save=s.save||readSave(),x=1730,y=760,hp=3200+level(save)*70;const boss=s.monsters.create(x,y,'boss');boss.setTint(0xc28cff).setScale(1.18).setSize(92,82).setData({name:'봉인파괴자 귀령',hp,maxHp:hp,damage:43,xp:1450,gold:1300,bornX:x,bornY:y,nextMove:0,isBoss:true,bossKey:`seal-dungeon-${clears(save)+1}-${Date.now()}`,rareItem:'moonRing',rareChance:.14,jw14Boss:true}).setDepth(y+30);s.bossEntity=boss;s.bossEntityKey=boss.getData('bossKey');try{s.tweens.add({targets:boss,scaleX:1.26,scaleY:1.26,duration:600,yoyo:true,repeat:-1});}catch{}attachLabel(s,boss,'봉인파괴자 귀령',true);toast('⚠ 봉인파괴자 귀령 출현 · 광역 공격을 피하세요!');const ch=ensureChapter4(save);if(ch.state===2){ch.state=3;writeSave(save,s);}renderQuest();}
function activateDungeon(s:any){if(!s?.player)return;dungeonScene=s;dungeonActive=true;dungeonKills=0;dungeonBossSpawned=false;destroyDungeonLabels();try{s.monsters?.clear?.(true,true);s.nodes?.clear?.(true,true);s.drops?.clear?.(true,true);s.bossEntity=undefined;s.bossEntityKey=undefined;s.map?.setTint?.(0x76678d);s.player.setPosition(280,780).setVelocity(0,0);}catch{}document.body.classList.add('jw-dungeon-active');const zone=document.querySelector<HTMLElement>('.zone strong');if(zone)zone.textContent='봉인동굴 · 권장 Lv.15+';spawnDungeonMobs(s);const save=s.save||readSave(),ch=ensureChapter4(save);if(ch.state===1){ch.state=2;ch.kills=0;writeSave(save,s);}updateDungeonHud();renderQuest();toast('봉인동굴 입장 · 자동사냥 사용 가능');}
function enterDungeon(){const s=scene(),save=s?.save||readSave();if(!s||!save)return;if(!chapter3Done(save)){toast('메인 임무 3장을 먼저 완료하세요.');return;}if(level(save)<15){toast('봉인동굴은 Lv.15부터 입장할 수 있습니다.');return;}const ch=ensureChapter4(save);if(ch.state===0){toast('촌장 백운에게 4장 임무를 먼저 받으세요.');questAction();return;}const meta=sceneMeta.get(s);if(!meta?.travel)return;stopAuto();if(dungeonActive)leaveDungeon();meta.travel('forest');window.setTimeout(()=>activateDungeon(s),260);}
function leaveDungeon(target?:string){const s=dungeonScene||scene();if(!s)return;dungeonActive=false;dungeonBossSpawned=false;document.body.classList.remove('jw-dungeon-active');destroyDungeonLabels();const meta=sceneMeta.get(s);if(target&&meta?.travel)meta.travel(target);else try{s.map?.clearTint?.();}catch{}dungeonScene=null;renderQuest();}
function restartDungeon(){const s=scene();if(!s)return;leaveDungeon();window.setTimeout(()=>enterDungeon(),120);}
function updateDungeonHud(){const hud=document.querySelector<HTMLElement>('.jw14-dungeon-hud');if(!hud)return;if(dungeonBossSpawned)hud.innerHTML='<b>봉인동굴 · 심층</b><small>봉인파괴자 귀령 격파</small>';else hud.innerHTML=`<b>봉인동굴 · 봉인수하 ${Math.min(dungeonKills,12)} / 12</b><small>${dungeonKills>=12?'심층 봉인이 깨지고 있습니다.':'12마리 토벌 후 심층 수호자 출현'}</small>`;}

function rewardDungeonBoss(s:any,save:any){if(!save)return;save.jw14SealCores=cores(save)+1;save.jw14DungeonClears=clears(save)+1;save.jw13Shards=shards(save)+6+ensureTalents(save).fortune;save.gold=Number(save.gold||0)+1500;save.potions=Number(save.potions||0)+2;if(!save.resources)save.resources={wood:0,herb:0,ore:0,crystal:0};save.resources.crystal=Number(save.resources.crystal||0)+2;const ch=ensureChapter4(save);if(ch.state===3){ch.state=4;ch.bossDone=true;}writeSave(save,s);renderGrowth();renderQuest();const layer=document.querySelector<HTMLElement>('.jw14-dungeon-clear');layer?.classList.remove('hidden');toast('봉인동굴 정화 · 봉인의 핵 +1 · 장비 파편 +6');}
function applyKillBonuses(s:any,monster:any,save:any){const t=ensureTalents(save),c=cores(save),baseGold=Math.max(0,Number(monster?.getData?.('gold')||0));const goldRate=t.mastery*.04+(c>=1?.05:0);if(goldRate>0)save.gold=Number(save.gold||0)+Math.max(1,Math.round(baseGold*goldRate));const healRate=t.mastery*.01+(c>=6?.03:0);if(healRate>0){const max=maxHpFromHud();save.hp=Math.min(max,Number(save.hp||0)+Math.max(1,Math.round(max*healRate)));}if(t.fortune>0&&Math.random()<t.fortune*.08)save.jw13Shards=shards(save)+1;writeSave(save,s);refreshHp(save);}
function patchScene(s:any){if(patchedScenes.has(s))return;const meta:{travel?:(zone:any)=>void}={};if(typeof s.travel==='function'){const original=s.travel.bind(s);meta.travel=original;s.travel=function(zone:any){if(dungeonActive){dungeonActive=false;document.body.classList.remove('jw-dungeon-active');destroyDungeonLabels();dungeonScene=null;}return original(zone);};}sceneMeta.set(s,meta);
 if(typeof s.contextAction==='function'){const original=s.contextAction.bind(s);s.contextAction=function(){const save=s.save||readSave();if(save&&chapter3Done(save)&&level(save)>=15&&String(s.zone)==='village'&&Phaser.Math.Distance.Between(s.player.x,s.player.y,1070,645)<135){const ch=ensureChapter4(save);if(ch.state===0){ch.state=1;ch.kills=0;save.gold=Number(save.gold||0)+400;writeSave(save,s);toast('메인 임무 4장 시작 · 봉인동굴 조사');renderQuest();return;}if(ch.state===4){if(!ch.rewarded){save.gold=Number(save.gold||0)+3200;save.potions=Number(save.potions||0)+5;save.jw13Shards=shards(save)+10;save.jw14Title='봉인 정화자';ch.rewarded=true;}ch.state=5;writeSave(save,s);toast('4장 완료 · 봉인 정화자 · 3,200엽전 · 파편 10');renderQuest();renderGrowth();return;}}return original();};}
 if(typeof s.defeat==='function'){const original=s.defeat.bind(s);s.defeat=function(monster:any){const isMob=!!monster?.getData?.('jw14DungeonMob'),isBoss=!!monster?.getData?.('jw14Boss'),already=!!monster?.getData?.('jw14Rewarded');if(isBoss&&!already)monster.setData?.('jw14Rewarded',true);const counted=!!monster?.getData?.('jw14Counted');original(monster);const save=s.save||readSave();if(save)applyKillBonuses(s,monster,save);if(dungeonActive&&isMob&&!counted){monster.setData?.('jw14Counted',true);dungeonKills++;const save2=s.save||readSave();if(save2){const ch=ensureChapter4(save2);if(ch.state===2){ch.kills=dungeonKills;writeSave(save2,s);}}updateDungeonHud();renderQuest();if(dungeonKills>=12)window.setTimeout(()=>spawnDungeonBoss(s),420);}if(isBoss&&!already){const save3=s.save||readSave();rewardDungeonBoss(s,save3);}};}
 if(typeof s.hurt==='function'){const original=s.hurt.bind(s);s.hurt=function(monster:any){const save=s.save||readSave(),before=Number(save?.hp||0);original(monster);const afterSave=s.save||readSave();if(!afterSave)return;const after=Number(afterSave.hp||0);if(after>=before)return;const t=ensureTalents(afterSave),c=cores(afterSave),rate=Math.min(.45,t.guard*.05+(c>=3?.08:0));if(rate<=0)return;const restored=Math.max(1,Math.round((before-after)*rate));afterSave.hp=Math.min(maxHpFromHud(),after+restored);writeSave(afterSave,s);refreshHp(afterSave);};}
 patchedScenes.add(s);}

function dungeonTick(s:any){if(!dungeonActive||s!==dungeonScene)return;if(String(s.zone)!=='forest'){leaveDungeon();return;}if(dungeonBossSpawned){for(const m of s.monsters?.getChildren?.()||[])if(m?.active&&m?.getData?.('jw14DungeonMob'))try{m.disableBody(true,true);}catch{}}updateLabels(s);updateDungeonHud();}
function setVersion(){document.querySelectorAll<HTMLElement>('.login-footer span').forEach(n=>{if(n.textContent?.includes('JUNJA WORLD'))n.textContent='JUNJA WORLD v1.4.0';});const badge=document.querySelector<HTMLElement>('.jw-v09-badge b');if(badge)badge.textContent='JUNJA WORLD v1.4.0';}
function tick(){const s=scene();if(s?.player){patchScene(s);dungeonTick(s);}const now=performance.now();if(now-lastUiRender>600){lastUiRender=now;renderQuest();renderGrowth();}}
function boot(){createUi();ensureGrowthBoxes();setVersion();renderQuest();renderGrowth();window.setInterval(tick,140);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
