import Phaser from 'phaser';
import './v22.css';

type Hero='warrior'|'mage'|'ranger';
type GearState={ornament:any;aura:any;title:any;lastRank:number;lastSignature:string};
const states=new WeakMap<any,GearState>();
const trackedGames=new Set<any>();

function installTracking(){const proto=(Phaser.Game as any)?.prototype;if(!proto||proto.__jwV22Tracked)return;const boot=proto.boot,destroy=proto.destroy;if(typeof boot==='function')proto.boot=function(...args:any[]){trackedGames.add(this);return boot.apply(this,args);};if(typeof destroy==='function')proto.destroy=function(...args:any[]){trackedGames.delete(this);return destroy.apply(this,args);};proto.__jwV22Tracked=true;}
installTracking();
function scene():any|null{const games=[...trackedGames,...((((Phaser as any).GAMES||[]) as any[]))];for(const game of games){const direct=game?.scene?.keys?.world;if(direct?.sys?.isActive?.())return direct;try{const s=game?.scene?.getScene?.('world');if(s?.sys?.isActive?.())return s;}catch{}}return null;}
function hero(s:any):Hero{return (s?.save?.heroClass||'warrior') as Hero;}
function make(s:any,key:string,w:number,h:number,draw:(g:any)=>void){if(s.textures?.exists?.(key))return;const g=s.add.graphics();draw(g);g.generateTexture(key,w,h);g.destroy();}
function textures(s:any){make(s,'jw22-ornament-warrior',72,56,g=>{g.fillStyle(0x162638,.98).fillRoundedRect(8,12,18,17,6).fillRoundedRect(46,12,18,17,6);g.fillStyle(0x6883a0).fillTriangle(6,19,26,9,24,30).fillTriangle(66,19,46,9,48,30);g.lineStyle(2,0xd9e4ec,.8).strokeRoundedRect(11,14,13,12,4).strokeRoundedRect(48,14,13,12,4);g.fillStyle(0xd9ad52).fillCircle(18,20,3).fillCircle(54,20,3);g.fillStyle(0x8f3232).fillTriangle(29,27,43,27,36,52);});make(s,'jw22-ornament-mage',72,72,g=>{g.fillStyle(0x4d376d,.85).fillRoundedRect(8,18,13,42,5).fillRoundedRect(51,18,13,42,5);g.lineStyle(2,0xd8c6f3,.78).strokeRoundedRect(8,18,13,42,5).strokeRoundedRect(51,18,13,42,5);g.fillStyle(0xf1cf6f).fillCircle(14,27,3).fillCircle(58,27,3).fillCircle(14,49,2).fillCircle(58,49,2);g.lineStyle(2,0x9e7ccc,.7).lineBetween(21,26,36,8).lineBetween(51,26,36,8);g.fillStyle(0xa77fd4,.45).fillCircle(36,10,9);});make(s,'jw22-ornament-ranger',72,70,g=>{g.fillStyle(0x5c432c,.96).fillRoundedRect(44,8,12,49,5);g.fillStyle(0x8f6b40).fillRoundedRect(47,11,6,43,3);g.lineStyle(2,0xd2b57a,.85).lineBetween(43,13,26,57).lineBetween(57,13,38,62);for(let i=0;i<4;i++){g.lineStyle(2,0xd8e2e8,.9).lineBetween(47+i*2,10,40+i*2,1);g.fillStyle(0xbddf78).fillTriangle(39+i*2,1,47+i*2,2,42+i*2,7);}g.fillStyle(0x476342,.85).fillTriangle(18,21,34,30,20,45);});}
function rankInfo(s:any){const w=Number(s?.save?.weaponLevel||0),a=Number(s?.save?.armorLevel||0),rare=Array.isArray(s?.save?.rareItems)&&s.save.rareItems.includes('blackIronBlade'),min=Math.min(w,a),max=Math.max(w,a);if(rare||min>=8)return {rank:4,label:rare?'신화 공명':'전설 공명',color:0xe8b4ff,glow:0xb56cff};if(min>=5)return {rank:3,label:'명품 공명',color:0xffdf7e,glow:0xe5ae3a};if(min>=3)return {rank:2,label:'정련 공명',color:0xa9ddff,glow:0x69bdea};if(max>0)return {rank:1,label:'수련 장비',color:0xd6dce2,glow:0x8ca6b8};return {rank:0,label:'초심 장비',color:0x9aa8b0,glow:0x66747c};}
function key(h:Hero){return h==='mage'?'jw22-ornament-mage':h==='ranger'?'jw22-ornament-ranger':'jw22-ornament-warrior';}
function createState(s:any){textures(s);const info=rankInfo(s),h=hero(s);const ornament=s.add.sprite(s.player.x,s.player.y,key(h)).setOrigin(.5).setVisible(info.rank>0).setDepth(s.player.y+17);const aura=s.add.ellipse(s.player.x,s.player.y+19,78,32,info.glow,.08).setStrokeStyle(info.rank>=2?3:2,info.glow,info.rank?0.58:0).setDepth(s.player.y-8).setVisible(info.rank>=2);const title=s.add.text(s.player.x,s.player.y-58,info.label,{fontFamily:'Noto Sans KR',fontSize:'8px',fontStyle:'bold',color:`#${info.color.toString(16).padStart(6,'0')}`,stroke:'#10191f',strokeThickness:3}).setOrigin(.5).setDepth(3002);const st={ornament,aura,title,lastRank:info.rank,lastSignature:''};states.set(s,st);return st;}
function burst(s:any,color:number){if(!s?.player)return;for(let i=0;i<12;i++){const a=Math.PI*2*i/12,r=Phaser.Math.Between(40,76);const p=s.add.circle(s.player.x,s.player.y,Phaser.Math.Between(2,4),color,.9).setDepth(s.player.y+120);s.tweens.add({targets:p,x:s.player.x+Math.cos(a)*r,y:s.player.y+Math.sin(a)*r*.7,alpha:0,scale:.25,duration:420,ease:'Quad.out',onComplete:()=>p.destroy()});}const ring=s.add.ellipse(s.player.x,s.player.y+14,54,24,0x000000,0).setStrokeStyle(4,color,.92).setDepth(s.player.y+110);s.tweens.add({targets:ring,scale:2.2,alpha:0,duration:420,onComplete:()=>ring.destroy()});}
function toast(label:string){let el=document.querySelector<HTMLElement>('.jw22-gear-toast');if(!el){el=document.createElement('div');el.className='jw22-gear-toast';document.body.appendChild(el);}el.innerHTML=`<b>장비 공명 강화</b><small>${label} 단계가 활성화되었습니다.</small>`;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');window.setTimeout(()=>el?.classList.remove('show'),1500);}
function update(s:any,st:GearState,time:number){const p=s.player;if(!p)return;const h=hero(s),info=rankInfo(s),w=Number(s.save?.weaponLevel||0),a=Number(s.save?.armorLevel||0),sig=`${h}:${w}:${a}:${info.rank}`;if(sig!==st.lastSignature){st.lastSignature=sig;st.ornament.setTexture(key(h)).setVisible(info.rank>0).setTint(info.color);st.aura.setVisible(info.rank>=2).setStrokeStyle(info.rank>=3?4:3,info.glow,.66).setFillStyle(info.glow,info.rank>=3?.11:.07);st.title.setText(info.label).setColor(`#${info.color.toString(16).padStart(6,'0')}`);if(info.rank>st.lastRank){burst(s,info.glow);toast(info.label);}st.lastRank=info.rank;}
 const f=s.facing||{x:0,y:1},side=f.x<0?-1:1,bob=Math.sin(time*.006)*(info.rank>=3?1.5:.7);const vertical=Math.abs(f.y)>Math.abs(f.x);if(h==='warrior'){st.ornament.setPosition(p.x,p.y-3+bob).setFlipX(false).setRotation(0).setDepth(vertical&&f.y<0?p.y-4:p.y+16);}else if(h==='mage'){st.ornament.setPosition(p.x-side*1,p.y-4+bob).setFlipX(side<0).setRotation(side*.025).setDepth(vertical&&f.y<0?p.y-6:p.y+15);}else{st.ornament.setPosition(p.x-side*8,p.y-2+bob).setFlipX(side<0).setRotation(side*.03).setDepth(vertical&&f.y<0?p.y-7:p.y+14);}st.aura.setPosition(p.x,p.y+20).setDepth(p.y-8).setRotation(time*.0007).setAlpha((info.rank>=2?.43:0)+Math.sin(time*.004)*.08);st.title.setPosition(p.x,p.y-57+bob*.25);if(info.rank>=3&&Math.random()<.035){const mote=s.add.circle(p.x+Phaser.Math.Between(-20,20),p.y+Phaser.Math.Between(8,28),2,info.glow,.72).setDepth(p.y+20);s.tweens.add({targets:mote,y:mote.y-38,alpha:0,duration:720,onComplete:()=>mote.destroy()});}}
function tick(){const s=scene();if(!s?.player)return;const st=states.get(s)||createState(s);update(s,st,performance.now());renderPanel(s);}
function renderPanel(s:any){let el=document.querySelector<HTMLElement>('.jw22-gear-status');if(!el){el=document.createElement('div');el.className='jw22-gear-status';document.body.appendChild(el);}const info=rankInfo(s),w=Number(s.save?.weaponLevel||0),a=Number(s.save?.armorLevel||0);el.innerHTML=`<b>${info.label}</b><span>무기 +${w} · 방어구 +${a}</span><small>${info.rank>=2?'세트 공명 활성':'무기·방어구 +3부터 공명 활성'}</small>`;el.className=`jw22-gear-status rank-${info.rank}`;}
function boot(){window.setInterval(tick,140);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
