import Phaser from 'phaser';
import './v05.css';
import { HERO_CLASSES, PLAYER_SPEED, WORLD_HEIGHT, WORLD_WIDTH, type HeroClass } from '../shared/constants';

type ZoneKey = 'village' | 'field' | 'mine' | 'forest';
type ResourceKey = 'wood' | 'herb' | 'ore' | 'crystal';
type SaveData = {
  name:string; heroClass:HeroClass; level:number; xp:number; hp:number; kills:number; quest:number;
  gold:number; potions:number; weaponLevel:number; armorLevel:number;
  resources:Record<ResourceKey,number>; crafted:number; unlocked:ZoneKey[];
};

type ZoneDef = {label:string; minLevel:number; tint:number; monsterTier:number; map:'world-map'|'field-map'};
const SAVE_KEY='junja-world-v01';
const ZONES:Record<ZoneKey,ZoneDef>={
  village:{label:'백운성',minLevel:1,tint:0xffffff,monsterTier:0,map:'world-map'},
  field:{label:'청운들판',minLevel:1,tint:0xffffff,monsterTier:1,map:'field-map'},
  mine:{label:'흑철광산',minLevel:5,tint:0xb9c3cf,monsterTier:2,map:'field-map'},
  forest:{label:'월영숲',minLevel:10,tint:0x9acb9b,monsterTier:3,map:'field-map'}
};
const RES_LABEL:Record<ResourceKey,string>={wood:'목재',herb:'약초',ore:'철광석',crystal:'월광결정'};

const q=<T extends Element>(s:string)=>document.querySelector<T>(s)!;
const ui={
  auth:q<HTMLElement>('#auth-layer'), game:q<HTMLElement>('#game-ui'), nameInput:q<HTMLInputElement>('#hero-name'), enter:q<HTMLButtonElement>('#enter-game'),
  classCards:[...document.querySelectorAll<HTMLButtonElement>('.class-card')], name:q<HTMLElement>('#ui-name'), heroClass:q<HTMLElement>('#ui-class'), hp:q<HTMLElement>('#hp-text'), hpBar:q<HTMLElement>('#hp-bar'), xp:q<HTMLElement>('#xp-text'), xpBar:q<HTMLElement>('#xp-bar'),
  atk:q<HTMLElement>('#atk-text'), kills:q<HTMLElement>('#kill-text'), gold:q<HTMLElement>('#gold-text'), quest:q<HTMLElement>('#quest-panel'), questTitle:q<HTMLElement>('#quest-title'), questText:q<HTMLElement>('#quest-text'), questBar:q<HTMLElement>('#quest-bar'),
  toast:q<HTMLElement>('#toast'), inventory:q<HTMLElement>('#inventory-panel'), inventoryBtn:q<HTMLButtonElement>('#inventory-button'), inventoryClose:q<HTMLButtonElement>('#inventory-close'), resourceText:q<HTMLElement>('#resource-text'), equipText:q<HTMLElement>('#equip-text'),
  usePotion:q<HTMLButtonElement>('#use-potion'), craftPotion:q<HTMLButtonElement>('#craft-potion'), craftWeapon:q<HTMLButtonElement>('#craft-weapon'), craftArmor:q<HTMLButtonElement>('#craft-armor'),
  mobileAttack:q<HTMLButtonElement>('#mobile-attack'), mobileAction:q<HTMLButtonElement>('#mobile-action'), reset:q<HTMLButtonElement>('#reset-save'), zoneButtons:[...document.querySelectorAll<HTMLButtonElement>('[data-zone]')], dragHint:q<HTMLElement>('#drag-hint')
};
let chosenClass:HeroClass='warrior'; let sceneRef:WorldScene|undefined; let game:Phaser.Game|undefined; let launchSave:SaveData|undefined; let toastTimer=0;

function fresh(name:string,heroClass:HeroClass):SaveData{return {name,heroClass,level:1,xp:0,hp:HERO_CLASSES[heroClass].maxHp,kills:0,quest:0,gold:0,potions:2,weaponLevel:0,armorLevel:0,resources:{wood:0,herb:0,ore:0,crystal:0},crafted:0,unlocked:['village','field']};}
function normalize(raw:any):SaveData|null{
  if(!raw?.name||!HERO_CLASSES[raw.heroClass as HeroClass])return null;
  return {...fresh(raw.name,raw.heroClass),...raw,quest:Number(raw.quest??0),resources:{wood:0,herb:0,ore:0,crystal:0,...(raw.resources||{})},unlocked:Array.isArray(raw.unlocked)?raw.unlocked:['village','field']};
}
function readSave(){try{return normalize(JSON.parse(localStorage.getItem(SAVE_KEY)||'null'));}catch{return null;}}
function persist(s:SaveData){localStorage.setItem(SAVE_KEY,JSON.stringify(s));}
function notify(msg:string){clearTimeout(toastTimer);ui.toast.textContent=msg;ui.toast.classList.remove('hidden');toastTimer=window.setTimeout(()=>ui.toast.classList.add('hidden'),2300);}
function maxHp(s:SaveData){return HERO_CLASSES[s.heroClass].maxHp+(s.level-1)*14+s.armorLevel*16;}
function attackPower(s:SaveData){return HERO_CLASSES[s.heroClass].attack+(s.level-1)*5+s.weaponLevel*5;}
function refreshHud(s:SaveData){
  const need=s.level*100; ui.name.textContent=s.name; ui.heroClass.textContent=`Lv.${s.level} ${HERO_CLASSES[s.heroClass].label}`; ui.hp.textContent=`${Math.max(0,Math.ceil(s.hp))} / ${maxHp(s)}`; ui.hpBar.style.width=`${Math.max(0,Math.min(100,s.hp/maxHp(s)*100))}%`; ui.xp.textContent=`${s.xp} / ${need}`; ui.xpBar.style.width=`${Math.min(100,s.xp/need*100)}%`; ui.atk.textContent=String(attackPower(s));ui.kills.textContent=String(s.kills);ui.gold.textContent=String(s.gold);
  const quests=[
    ['낯선 마을의 부름','촌장 백운을 찾아가자. · 클릭하면 자동이동','12%'],
    ['청운들판 토벌',`청운들판 요괴 5마리 처치 (${Math.min(s.kills,5)}/5) · 클릭하면 이동`,'48%'],
    ['백운에게 보고','촌장 백운에게 돌아가 보상을 받자. · 클릭하면 자동이동','82%'],
    ['흑철광산 조사',`Lv.5 달성 후 흑철광산에서 철광석 5개 채집 (${Math.min(s.resources.ore,5)}/5)`,'92%'],
    ['월영숲의 문','Lv.10을 달성하고 월영숲의 상위 몬스터를 상대하자.','100%']
  ]; const qq=quests[Math.min(s.quest,quests.length-1)];ui.questTitle.textContent=qq[0];ui.questText.textContent=qq[1];ui.questBar.style.width=qq[2];
  ui.resourceText.textContent=`목재 ${s.resources.wood} · 약초 ${s.resources.herb} · 철광석 ${s.resources.ore} · 결정 ${s.resources.crystal}`;
  ui.equipText.textContent=`무기 +${s.weaponLevel} · 방어구 +${s.armorLevel} · 회복약 ${s.potions}`;
  ui.zoneButtons.forEach(b=>{const z=b.dataset.zone as ZoneKey; b.classList.toggle('locked',s.level<ZONES[z].minLevel);b.title=s.level<ZONES[z].minLevel?`Lv.${ZONES[z].minLevel} 필요`:ZONES[z].label;});
}
function startGame(s:SaveData){ui.auth.classList.add('hidden');ui.game.classList.remove('hidden');launchSave=s;refreshHud(s);game?.destroy(true);game=new Phaser.Game({type:Phaser.AUTO,parent:'game-container',width:innerWidth,height:innerHeight,backgroundColor:'#182a22',physics:{default:'arcade',arcade:{gravity:{x:0,y:0},debug:false}},scale:{mode:Phaser.Scale.RESIZE,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[WorldScene]});}
ui.classCards.forEach(c=>c.addEventListener('click',()=>{chosenClass=c.dataset.class as HeroClass;ui.classCards.forEach(x=>x.classList.toggle('selected',x===c));}));
const existing=readSave();if(existing){ui.nameInput.value=existing.name;chosenClass=existing.heroClass;ui.enter.textContent=`${existing.name}로 계속하기`;ui.classCards.forEach(c=>c.classList.toggle('selected',c.dataset.class===chosenClass));}
ui.enter.addEventListener('click',()=>{const name=ui.nameInput.value.trim()||'준자',old=readSave();startGame(old&&old.name===name&&old.heroClass===chosenClass?old:fresh(name,chosenClass));});
ui.nameInput.addEventListener('keydown',e=>{if(e.key==='Enter')ui.enter.click();});ui.reset.addEventListener('click',()=>{if(confirm('현재 캐릭터 기록을 지우고 처음부터 시작할까?')){localStorage.removeItem(SAVE_KEY);location.reload();}});
ui.quest.addEventListener('click',()=>sceneRef?.questNavigate());ui.inventoryBtn.addEventListener('click',()=>sceneRef?.toggleInventory());ui.inventoryClose.addEventListener('click',()=>sceneRef?.toggleInventory(false));ui.mobileAttack.addEventListener('pointerdown',()=>sceneRef?.attack());ui.mobileAction.addEventListener('pointerdown',()=>sceneRef?.contextAction());ui.usePotion.addEventListener('click',()=>sceneRef?.usePotion());ui.craftPotion.addEventListener('click',()=>sceneRef?.craft('potion'));ui.craftWeapon.addEventListener('click',()=>sceneRef?.craft('weapon'));ui.craftArmor.addEventListener('click',()=>sceneRef?.craft('armor'));ui.zoneButtons.forEach(b=>b.addEventListener('click',()=>sceneRef?.travel(b.dataset.zone as ZoneKey)));

class WorldScene extends Phaser.Scene{
  private save!:SaveData; private zone:ZoneKey='village'; private player!:Phaser.Physics.Arcade.Sprite; private nameText!:Phaser.GameObjects.Text; private shadow!:Phaser.GameObjects.Ellipse; private elder!:Phaser.GameObjects.Container; private map!:Phaser.GameObjects.Image;
  private monsters!:Phaser.Physics.Arcade.Group; private nodes!:Phaser.Physics.Arcade.Group; private drops!:Phaser.Physics.Arcade.Group; private cursors!:Phaser.Types.Input.Keyboard.CursorKeys; private keys!:Record<string,Phaser.Input.Keyboard.Key>; private facing=new Phaser.Math.Vector2(0,1); private dragVector=new Phaser.Math.Vector2(); private dragStart?:Phaser.Math.Vector2; private autoTarget?:Phaser.Math.Vector2; private inventoryOpen=false; private lastAttack=0; private lastHurt=0; private actionLabel?:Phaser.GameObjects.Text;
  constructor(){super('world');}
  init(){this.save={...(launchSave??fresh('준자','warrior'))};sceneRef=this;}
  preload(){this.load.image('world-map','/assets/baegun-village.webp');this.load.image('field-map','/assets/cheongun-field-v1.webp');this.load.spritesheet('hero-warrior','/assets/hero-warrior-sheet.webp',{frameWidth:300,frameHeight:300});this.load.spritesheet('hero-mage','/assets/hero-mage-sheet.webp',{frameWidth:300,frameHeight:300});this.load.spritesheet('hero-ranger','/assets/hero-ranger-sheet.webp',{frameWidth:300,frameHeight:300});this.load.spritesheet('slime','/assets/dokkaebi-slime-sheet.webp',{frameWidth:500,frameHeight:500});this.load.image('elder-art','/assets/elder-baegun-trim.webp');}
  create(){this.makeTextures();this.makeAnimations();this.physics.world.setBounds(0,0,WORLD_WIDTH,WORLD_HEIGHT);this.map=this.add.image(WORLD_WIDTH/2,WORLD_HEIGHT/2,'world-map').setDisplaySize(WORLD_WIDTH,WORLD_HEIGHT).setDepth(-20);this.createPlayer();this.createElder();this.monsters=this.physics.add.group();this.nodes=this.physics.add.group({allowGravity:false,immovable:true});this.drops=this.physics.add.group({allowGravity:false});this.physics.add.overlap(this.player,this.monsters,(_p,m)=>this.hurt(m as Phaser.Physics.Arcade.Sprite));this.physics.add.overlap(this.player,this.drops,(_p,d)=>this.collectDrop(d as Phaser.Physics.Arcade.Sprite));this.bindControls();this.cameras.main.setBounds(0,0,WORLD_WIDTH,WORLD_HEIGHT);this.cameras.main.startFollow(this.player,true,.1,.1);this.enterZone('village',1160,790,false);refreshHud(this.save);persist(this.save);this.time.delayedCall(500,()=>notify('화면을 드래그해서 이동하세요. 퀘스트를 누르면 목적지로 이동합니다.'));}
  private makeTextures(){const make=(k:string,w:number,h:number,draw:(g:Phaser.GameObjects.Graphics)=>void)=>{if(this.textures.exists(k))return;const g=this.add.graphics();draw(g);g.generateTexture(k,w,h);g.destroy();};make('node-tree',52,68,g=>{g.fillStyle(0x6a4524).fillRect(22,32,9,34);g.fillStyle(0x317147).fillCircle(15,28,16).fillCircle(37,25,18).fillCircle(27,12,20);});make('node-herb',44,44,g=>{g.fillStyle(0x68ba69);for(let i=0;i<5;i++)g.fillEllipse(22+(i-2)*5,24-Math.abs(i-2)*5,12,24);});make('node-ore',50,42,g=>{g.fillStyle(0x68747e).fillTriangle(3,38,17,8,30,20).fillTriangle(15,38,34,4,48,38);g.fillStyle(0xb7c8d8).fillTriangle(25,22,34,4,38,25);});make('node-crystal',46,55,g=>{g.fillStyle(0x86d6ef,.9).fillTriangle(23,2,41,43,23,53).fillTriangle(23,2,5,43,23,53);});make('coin',22,22,g=>g.fillStyle(0xf0c453).fillCircle(11,11,9));}
  private makeAnimations(){const frames={down:[1,4,1],up:[2,3,2],side:[7,9,7]};(Object.keys(HERO_CLASSES) as HeroClass[]).forEach(c=>Object.entries(frames).forEach(([d,n])=>{const k=`walk-${c}-${d}`;if(!this.anims.exists(k))this.anims.create({key:k,frames:this.anims.generateFrameNumbers(`hero-${c}`,{frames:n}),frameRate:7,repeat:-1});}));if(!this.anims.exists('slime-idle'))this.anims.create({key:'slime-idle',frames:this.anims.generateFrameNumbers('slime',{frames:[0,1,2,1]}),frameRate:4,repeat:-1});}
  private createPlayer(){this.shadow=this.add.ellipse(1160,815,38,12,0x10251d,.35);this.player=this.physics.add.sprite(1160,790,`hero-${this.save.heroClass}`,1).setScale(.24).setCollideWorldBounds(true);this.player.setSize(70,86).setOffset(115,196);this.nameText=this.add.text(1160,738,this.save.name,{fontFamily:'Noto Sans KR',fontSize:'11px',fontStyle:'bold',color:'#fff',stroke:'#14232b',strokeThickness:4}).setOrigin(.5).setDepth(3000);}
  private createElder(){const art=this.add.image(0,18,'elder-art').setScale(.058);const mark=this.add.text(0,-70,'!',{fontFamily:'serif',fontSize:'30px',fontStyle:'bold',color:'#ffd55c',stroke:'#47320b',strokeThickness:6}).setOrigin(.5);const label=this.add.text(0,72,'촌장 백운',{fontFamily:'Noto Sans KR',fontSize:'12px',fontStyle:'bold',color:'#fff1c8',stroke:'#13212a',strokeThickness:5}).setOrigin(.5);this.elder=this.add.container(1070,645,[art,mark,label]).setDepth(2000);}
  private bindControls(){this.cursors=this.input.keyboard!.createCursorKeys();this.keys=this.input.keyboard!.addKeys('W,A,S,D,E,I,SPACE') as Record<string,Phaser.Input.Keyboard.Key>;this.keys.SPACE.on('down',()=>this.attack());this.keys.E.on('down',()=>this.contextAction());this.keys.I.on('down',()=>this.toggleInventory());
    this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>{if(!p.event||this.isUiTarget(p.event.target as Element))return;this.autoTarget=undefined;this.dragStart=new Phaser.Math.Vector2(p.x,p.y);this.dragVector.set(0,0);ui.dragHint.classList.remove('hidden');});
    this.input.on('pointermove',(p:Phaser.Input.Pointer)=>{if(!p.isDown||!this.dragStart)return;const delta=new Phaser.Math.Vector2(p.x-this.dragStart.x,p.y-this.dragStart.y);if(delta.length()<10)this.dragVector.set(0,0);else this.dragVector.copy(delta).limit(90).scale(1/90);});
    const end=()=>{this.dragStart=undefined;this.dragVector.set(0,0);ui.dragHint.classList.add('hidden');};this.input.on('pointerup',end);this.input.on('pointerupoutside',end);
  }
  private isUiTarget(el:Element|null){return !!el?.closest('#game-ui button,#game-ui aside,.top-bar,.dialogue');}
  update(time:number){if(!this.player.active)return;let x=(this.cursors.left.isDown||this.keys.A.isDown?-1:0)+(this.cursors.right.isDown||this.keys.D.isDown?1:0)+this.dragVector.x;let y=(this.cursors.up.isDown||this.keys.W.isDown?-1:0)+(this.cursors.down.isDown||this.keys.S.isDown?1:0)+this.dragVector.y;
    if(this.autoTarget&&!this.inventoryOpen){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,this.autoTarget.x,this.autoTarget.y);if(d<28){this.autoTarget=undefined;notify('목적지에 도착했습니다.');}else{const v=new Phaser.Math.Vector2(this.autoTarget.x-this.player.x,this.autoTarget.y-this.player.y).normalize();x=v.x;y=v.y;}}
    const v=new Phaser.Math.Vector2(x,y);if(v.lengthSq()>1)v.normalize();v.scale(this.inventoryOpen?0:PLAYER_SPEED);this.player.setVelocity(v.x,v.y);this.animatePlayer(v,time);this.updateMonsters(time);this.nameText.setPosition(this.player.x,this.player.y-52);this.shadow.setPosition(this.player.x,this.player.y+25).setDepth(this.player.y-2);this.player.setDepth(this.player.y+20);this.updateContext();}
  private animatePlayer(v:Phaser.Math.Vector2,_time:number){if(v.lengthSq()>0){this.facing.copy(v).normalize();const d=Math.abs(v.x)>Math.abs(v.y)?(v.x<0?'left':'right'):(v.y<0?'up':'down');if(d==='left'||d==='right')this.player.setFlipX(d==='right').play(`walk-${this.save.heroClass}-side`,true);else this.player.setFlipX(false).play(`walk-${this.save.heroClass}-${d}`,true);}else{this.player.stop();const d=Math.abs(this.facing.x)>Math.abs(this.facing.y)?(this.facing.x<0?'left':'right'):(this.facing.y<0?'up':'down');if(d==='left'||d==='right')this.player.setFrame(7).setFlipX(d==='right');else this.player.setFrame(d==='up'?2:1).setFlipX(false);}}
  private spawnZone(){this.monsters.clear(true,true);this.nodes.clear(true,true);if(this.zone==='village')return;const tier=ZONES[this.zone].monsterTier;const names=tier===1?['들슬라임','푸른 물방울','도깨비불']:tier===2?['광산박쥐','흑철골렘','동굴도깨비']:['월영늑대','그림자요괴','고목정령'];for(let i=0;i<12;i++){const x=350+(i%4)*520+Phaser.Math.Between(-80,80),y=260+Math.floor(i/4)*390+Phaser.Math.Between(-70,70);const hp=45+tier*55+i*3,damage=6+tier*7,xp=18+tier*32,gold=10+tier*18;const m=this.monsters.create(x,y,'slime') as Phaser.Physics.Arcade.Sprite;m.setScale(.09+tier*.018).setTint(tier===1?0xffffff:tier===2?0xaab5c5:0x9b7cff).setSize(260,180).setOffset(120,300).setData({name:names[i%names.length],hp,maxHp:hp,damage,xp,gold,bornX:x,bornY:y,nextMove:0}).play('slime-idle');}
    const nodeType:ResourceKey=this.zone==='field'?'herb':this.zone==='mine'?'ore':'crystal';const tex=this.zone==='field'?'node-herb':this.zone==='mine'?'node-ore':'node-crystal';for(let i=0;i<9;i++){const n=this.nodes.create(280+(i%3)*780+Phaser.Math.Between(-80,80),240+Math.floor(i/3)*430+Phaser.Math.Between(-60,60),tex) as Phaser.Physics.Arcade.Sprite;n.setData({kind:nodeType,amount:this.zone==='forest'?1:Phaser.Math.Between(1,2),ready:true});}if(this.zone==='field'){for(let i=0;i<6;i++){const n=this.nodes.create(420+(i%3)*650,420+Math.floor(i/3)*500,'node-tree') as Phaser.Physics.Arcade.Sprite;n.setData({kind:'wood',amount:Phaser.Math.Between(1,2),ready:true});}}
  }
  private updateMonsters(time:number){this.monsters.getChildren().forEach(o=>{const m=o as Phaser.Physics.Arcade.Sprite;if(!m.active)return;const d=Phaser.Math.Distance.Between(m.x,m.y,this.player.x,this.player.y);if(d<280)this.physics.moveToObject(m,this.player,48+ZONES[this.zone].monsterTier*12);else if(time>(m.getData('nextMove')||0)){m.setData('nextMove',time+Phaser.Math.Between(1300,2600));m.setVelocity(Phaser.Math.Between(-45,45),Phaser.Math.Between(-45,45));}m.setFlipX((m.body as Phaser.Physics.Arcade.Body).velocity.x<0);m.setDepth(m.y+10);});}
  private updateContext(){if(this.actionLabel){this.actionLabel.destroy();this.actionLabel=undefined;}const node=this.nearestNode(90);const elderNear=this.zone==='village'&&Phaser.Math.Distance.Between(this.player.x,this.player.y,1070,645)<120;if(node||elderNear){const text=node?`${RES_LABEL[node.getData('kind') as ResourceKey]} 채집 · E / 행동`:'촌장과 대화 · E / 행동';this.actionLabel=this.add.text(this.player.x,this.player.y-85,text,{fontFamily:'Noto Sans KR',fontSize:'11px',color:'#fff2bd',stroke:'#18232a',strokeThickness:5}).setOrigin(.5).setDepth(4000);}}
  private nearestNode(radius:number){let best:Phaser.Physics.Arcade.Sprite|undefined,dist=radius;this.nodes.getChildren().forEach(o=>{const n=o as Phaser.Physics.Arcade.Sprite;if(!n.active||!n.getData('ready'))return;const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,n.x,n.y);if(d<dist){dist=d;best=n;}});return best;}
  contextAction(){const node=this.nearestNode(100);if(node){this.gather(node);return;}if(this.zone==='village'&&Phaser.Math.Distance.Between(this.player.x,this.player.y,1070,645)<130){this.talk();return;}notify('가까운 NPC나 채집물이 없습니다.');}
  private gather(node:Phaser.Physics.Arcade.Sprite){const kind=node.getData('kind') as ResourceKey,amount=node.getData('amount') as number;node.setData('ready',false).setAlpha(.2).disableBody(true,false);this.save.resources[kind]+=amount;notify(`${RES_LABEL[kind]} +${amount}`);if(this.save.quest===3&&kind==='ore'&&this.save.resources.ore>=5){this.save.quest=4;notify('흑철광산 조사 완료! 이제 Lv.10 월영숲을 향해 성장하세요.');}persist(this.save);refreshHud(this.save);this.time.delayedCall(12000,()=>{if(node.scene){node.enableBody(false,node.x,node.y,true,true).setAlpha(1);node.setData('ready',true);}});}
  private talk(){if(this.save.quest===0){this.save.quest=1;notify('임무 시작: 청운들판 요괴 5마리 토벌');this.time.delayedCall(650,()=>this.travel('field'));}else if(this.save.quest===2){this.save.quest=3;this.save.gold+=300;this.save.potions+=3;this.gainXp(220);notify('토벌 완료 · 300엽전 · 회복약 3 · EXP +220');}else notify('재료를 모아 장비를 만들고 더 높은 지역에 도전하게.');persist(this.save);refreshHud(this.save);}
  questNavigate(){if(this.save.quest===0||this.save.quest===2){if(this.zone!=='village')this.enterZone('village',1160,790,true);this.autoTarget=new Phaser.Math.Vector2(1070,720);notify('촌장 백운에게 자동이동합니다.');}else if(this.save.quest===1){this.travel('field');}else if(this.save.quest===3){this.travel('mine');}else{this.travel('forest');}}
  travel(zone:ZoneKey){const min=ZONES[zone].minLevel;if(this.save.level<min){notify(`${ZONES[zone].label}은 Lv.${min}부터 입장할 수 있습니다.`);return;}this.enterZone(zone,zone==='village'?1160:260,zone==='village'?790:680,true);}
  private enterZone(zone:ZoneKey,x:number,y:number,flash=true){this.zone=zone;this.map.setTexture(ZONES[zone].map).setTint(ZONES[zone].tint);this.player.setPosition(x,y).setVelocity(0,0);this.autoTarget=undefined;this.elder.setVisible(zone==='village');this.spawnZone();q<HTMLElement>('.zone strong').textContent=`${ZONES[zone].label} · 권장 Lv.${ZONES[zone].minLevel}+`;if(flash){this.cameras.main.flash(280,240,215,150);notify(`${ZONES[zone].label}에 도착했습니다.`);} }
  attack(){if(this.inventoryOpen||this.time.now-this.lastAttack<380)return;this.lastAttack=this.time.now;const point=new Phaser.Math.Vector2(this.player.x,this.player.y).add(this.facing.clone().scale(62));let target:Phaser.Physics.Arcade.Sprite|undefined,dist=115;this.monsters.getChildren().forEach(o=>{const m=o as Phaser.Physics.Arcade.Sprite;if(!m.active)return;const d=Phaser.Math.Distance.Between(point.x,point.y,m.x,m.y);if(d<dist){dist=d;target=m;}});const slash=this.add.arc(point.x,point.y,44,220,500,false,0xffd877,.28).setStrokeStyle(5,0xffefb0,.9).setDepth(3500);this.tweens.add({targets:slash,alpha:0,scale:1.3,duration:160,onComplete:()=>slash.destroy()});if(!target)return;const m=target as Phaser.Physics.Arcade.Sprite,damage=Math.max(1,attackPower(this.save)+Phaser.Math.Between(-4,6));m.setData('hp',(m.getData('hp') as number)-damage);if((m.getData('hp') as number)<=0)this.defeat(m);}
  private defeat(m:Phaser.Physics.Arcade.Sprite){const x=m.x,y=m.y,xp=m.getData('xp') as number,gold=m.getData('gold') as number,name=m.getData('name') as string,bx=m.getData('bornX') as number,by=m.getData('bornY') as number,max=m.getData('maxHp') as number;m.disableBody(true,true);this.save.kills++;this.save.gold+=gold;this.gainXp(xp);if(this.save.quest===1&&this.save.kills>=5){this.save.quest=2;notify('토벌 목표 달성! 퀘스트를 눌러 백운에게 돌아가세요.');}else notify(`${name} 처치 · EXP +${xp} · ${gold}엽전`);const coin=this.drops.create(x,y,'coin') as Phaser.Physics.Arcade.Sprite;coin.setData({kind:'gold',amount:Phaser.Math.Between(2,8)});this.time.delayedCall(8000,()=>{if(m.scene&&this.zone!=='village'){m.enableBody(true,bx+Phaser.Math.Between(-50,50),by+Phaser.Math.Between(-50,50),true,true);m.setData('hp',max);}});persist(this.save);refreshHud(this.save);}
  private collectDrop(d:Phaser.Physics.Arcade.Sprite){this.save.gold+=d.getData('amount') as number;d.destroy();persist(this.save);refreshHud(this.save);}
  private hurt(m:Phaser.Physics.Arcade.Sprite){if(this.time.now-this.lastHurt<900)return;this.lastHurt=this.time.now;const reduction=Math.min(.45,this.save.armorLevel*.04);this.save.hp-=Math.max(1,Math.round((m.getData('damage') as number)*(1-reduction)));if(this.save.hp<=0){this.save.hp=maxHp(this.save);this.enterZone('village',1160,790,true);notify('기력이 다해 백운성에서 회복했습니다.');}persist(this.save);refreshHud(this.save);}
  private gainXp(amount:number){this.save.xp+=amount;while(this.save.xp>=this.save.level*100){this.save.xp-=this.save.level*100;this.save.level++;this.save.hp=maxHp(this.save);if(this.save.level>=5&&!this.save.unlocked.includes('mine'))this.save.unlocked.push('mine');if(this.save.level>=10&&!this.save.unlocked.includes('forest'))this.save.unlocked.push('forest');notify(`레벨 업! Lv.${this.save.level}`);} }
  toggleInventory(force?:boolean){this.inventoryOpen=force??!this.inventoryOpen;ui.inventory.classList.toggle('hidden',!this.inventoryOpen);if(this.inventoryOpen)this.player.setVelocity(0,0);}
  usePotion(){if(this.save.potions<1){notify('회복약이 없습니다.');return;}if(this.save.hp>=maxHp(this.save)){notify('체력이 가득 찼습니다.');return;}this.save.potions--;this.save.hp=Math.min(maxHp(this.save),this.save.hp+65);persist(this.save);refreshHud(this.save);notify('체력 +65');}
  craft(kind:'potion'|'weapon'|'armor'){if(kind==='potion'){if(this.save.resources.herb<3){notify('약초 3개가 필요합니다.');return;}this.save.resources.herb-=3;this.save.potions+=2;notify('회복약 2개 제작 완료');}else if(kind==='weapon'){const ore=2+this.save.weaponLevel*2,wood=2;if(this.save.resources.ore<ore||this.save.resources.wood<wood){notify(`철광석 ${ore} · 목재 ${wood} 필요`);return;}this.save.resources.ore-=ore;this.save.resources.wood-=wood;this.save.weaponLevel++;notify(`무기 제작/강화 성공 · +${this.save.weaponLevel}`);}else{const ore=3+this.save.armorLevel*2,crystal=this.save.armorLevel>=2?1:0;if(this.save.resources.ore<ore||this.save.resources.crystal<crystal){notify(`철광석 ${ore}${crystal?` · 월광결정 ${crystal}`:''} 필요`);return;}this.save.resources.ore-=ore;this.save.resources.crystal-=crystal;this.save.armorLevel++;this.save.hp=maxHp(this.save);notify(`방어구 제작/강화 성공 · +${this.save.armorLevel}`);}this.save.crafted++;persist(this.save);refreshHud(this.save);}
}
