import Phaser from 'phaser';
import './v20.css';

type TargetState={target:any|null;ring:any|null;index:number;zone:string};
const trackedGames=new Set<any>();
const states=new WeakMap<any,TargetState>();

function installTracking(){const proto=(Phaser.Game as any)?.prototype;if(!proto||proto.__jwV20Tracked)return;const boot=proto.boot,destroy=proto.destroy;if(typeof boot==='function')proto.boot=function(...args:any[]){trackedGames.add(this);return boot.apply(this,args);};if(typeof destroy==='function')proto.destroy=function(...args:any[]){trackedGames.delete(this);return destroy.apply(this,args);};proto.__jwV20Tracked=true;}
installTracking();
function scene():any|null{const games=[...trackedGames,...((((Phaser as any).GAMES||[]) as any[]))];for(const game of games){const direct=game?.scene?.keys?.world;if(direct?.sys?.isActive?.())return direct;try{const s=game?.scene?.getScene?.('world');if(s?.sys?.isActive?.())return s;}catch{}}return null;}
function alive(m:any){return !!m&&m.active!==false&&m.visible!==false&&!m.destroyed&&Number(m.getData?.('hp')||0)>0;}
function candidates(s:any){if(!s?.player)return[];const list=(s.monsters?.getChildren?.()||[]).filter((m:any)=>alive(m));if(alive(s?.bossEntity)&&!list.includes(s.bossEntity))list.push(s.bossEntity);return list.sort((a:any,b:any)=>Phaser.Math.Distance.Between(s.player.x,s.player.y,a.x,a.y)-Phaser.Math.Distance.Between(s.player.x,s.player.y,b.x,b.y));}
function createUi(){if(!document.querySelector('.jw20-target-hud')){const hud=document.createElement('div');hud.className='jw20-target-hud hidden-target';hud.innerHTML='<div class="jw20-target-top"><div id="jw20-target-name" class="jw20-target-name">대상 없음</div><div id="jw20-target-kind" class="jw20-target-kind">TARGET</div></div><div class="jw20-target-bar"><i id="jw20-target-fill"></i></div><div class="jw20-target-bottom"><span id="jw20-target-hp">HP -</span><span id="jw20-target-distance">거리 -</span></div>';document.body.appendChild(hud);}if(!document.querySelector('.jw20-target-button')){const b=document.createElement('button');b.type='button';b.className='jw20-target-button';b.innerHTML='타깃 전환<small>PC TAB</small>';b.addEventListener('click',()=>cycleTarget(1));document.body.appendChild(b);}}
function ensureState(s:any){let state=states.get(s);if(!state){state={target:null,ring:null,index:-1,zone:String(s.zone||'village')};states.set(s,state);}return state;}
function ensureRing(s:any,state:TargetState){if(state.ring?.scene)return state.ring;state.ring=s.add.ellipse(0,0,92,46,0x000000,0).setStrokeStyle(4,0xe5c66b,.95).setDepth(4800).setVisible(false);s.tweens.add({targets:state.ring,scaleX:{from:.92,to:1.08},scaleY:{from:.92,to:1.08},alpha:{from:.55,to:1},duration:620,yoyo:true,repeat:-1,ease:'Sine.inOut'});return state.ring;}
function classify(m:any){if(m?.getData?.('isBoss'))return 'BOSS';if(m?.getData?.('jwElite'))return 'ELITE';return String(m?.getData?.('jw16Archetype')||'MONSTER').toUpperCase();}
function setTarget(s:any,target:any|null){const state=ensureState(s);state.target=target;const ring=ensureRing(s,state);if(!target){ring.setVisible(false);renderHud(null,s);return;}const list=candidates(s);state.index=Math.max(0,list.indexOf(target));ring.setVisible(true);ring.setStrokeStyle(target.getData?.('isBoss')?5:target.getData?.('jwElite')?4:3,target.getData?.('isBoss')?0xffd266:target.getData?.('jwElite')?0xe6a5ff:0xe5c66b,.95);renderHud(target,s);}
function cycleTarget(step=1){const s=scene();if(!s?.player||String(s.zone)==='village')return;const list=candidates(s),state=ensureState(s);if(!list.length){setTarget(s,null);return;}let idx=state.target?list.indexOf(state.target):-1;if(idx<0)idx=-1;idx=(idx+step+list.length)%list.length;setTarget(s,list[idx]);}
function nearestAuto(s:any,state:TargetState){if(String(s.zone)==='village'){if(state.target)setTarget(s,null);return;}if(alive(state.target))return;const list=candidates(s);const near=list.find((m:any)=>Phaser.Math.Distance.Between(s.player.x,s.player.y,m.x,m.y)<=520);setTarget(s,near||null);}
function renderHud(target:any|null,s:any){const hud=document.querySelector<HTMLElement>('.jw20-target-hud'),name=document.querySelector<HTMLElement>('#jw20-target-name'),kind=document.querySelector<HTMLElement>('#jw20-target-kind'),fill=document.querySelector<HTMLElement>('#jw20-target-fill'),hp=document.querySelector<HTMLElement>('#jw20-target-hp'),dist=document.querySelector<HTMLElement>('#jw20-target-distance'),btn=document.querySelector<HTMLElement>('.jw20-target-button');if(!hud||!name||!kind||!fill||!hp||!dist)return;if(!target||!alive(target)||String(s.zone)==='village'){hud.classList.add('hidden-target');btn?.classList.remove('active');return;}hud.classList.remove('hidden-target');btn?.classList.add('active');const max=Math.max(1,Number(target.getData?.('maxHp')||target.getData?.('hp')||1)),cur=Math.max(0,Number(target.getData?.('hp')||0)),d=Math.round(Phaser.Math.Distance.Between(s.player.x,s.player.y,target.x,target.y));name.textContent=String(target.getData?.('name')||'요괴');kind.textContent=classify(target);fill.style.width=`${Math.max(0,Math.min(100,cur/max*100))}%`;hp.textContent=`HP ${Math.ceil(cur)} / ${Math.ceil(max)}`;dist.innerHTML=`거리 <b>${d}</b>`;}
function updateRing(s:any,state:TargetState){const target=state.target,ring=ensureRing(s,state);if(!alive(target)){if(target)setTarget(s,null);return;}ring.setPosition(target.x,target.y+Math.max(20,Number(target.displayHeight||70)*.28)).setDepth(target.y+95).setDisplaySize(Math.max(58,Number(target.displayWidth||72)*.86),Math.max(28,Number(target.displayHeight||60)*.32));renderHud(target,s);}
function bindKeys(){window.addEventListener('keydown',(e:KeyboardEvent)=>{const target=e.target as HTMLElement|null;if(target?.matches('input,textarea,select,[contenteditable="true"]'))return;if(e.code==='Tab'){e.preventDefault();cycleTarget(e.shiftKey?-1:1);}});}
function tick(){createUi();const s=scene();if(!s?.player)return;const state=ensureState(s),zone=String(s.zone||'village');if(state.zone!==zone){state.zone=zone;setTarget(s,null);}nearestAuto(s,state);updateRing(s,state);}
function boot(){createUi();bindKeys();window.setInterval(tick,120);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
