import Phaser from 'phaser';
import './v23.css';

type Service='forge'|'guide'|'trainer'|'healer';
type HubNpc={id:string;name:string;role:string;x:number;y:number;robe:number;accent:number;service:Service;intro:string};
type HubState={npcs:any[];zone:string;nearest:any|null;marker:any|null};
const states=new WeakMap<any,HubState>();
const trackedGames=new Set<any>();
const defs:HubNpc[]=[
 {id:'taebaek',name:'대장장이 태백',role:'장비 제작 · 공명',x:1020,y:865,robe:0x704439,accent:0xe0a34d,service:'forge',intro:'좋은 장비는 사냥터에서 완성되는 법이지. 재료가 있다면 바로 제작소를 열어주마.'},
 {id:'seolhwa',name:'길드 안내원 설화',role:'성장 동선 · 콘텐츠 안내',x:1160,y:795,robe:0x4d5f7d,accent:0xc8d5f1,service:'guide',intro:'지금 어디서 뭘 해야 할지 막히면 말해. 현재 레벨과 장비에 맞는 다음 목표를 알려줄게.'},
 {id:'muyang',name:'수련교관 무영',role:'전투 훈련 · 출정',x:1450,y:880,robe:0x4b5b42,accent:0xe0c76f,service:'trainer',intro:'백운성 밖에서는 손이 느리면 바로 눕는다. 준비됐으면 청운들판으로 보내주지.'},
 {id:'harin',name:'의원 하린',role:'무료 치료 · 휴식',x:720,y:800,robe:0x6a4f69,accent:0xf0c8de,service:'healer',intro:'모험가가 쓰러지는 건 아까운 일이죠. 백운성에서는 언제든 몸을 회복시켜 드릴게요.'}
];

function installTracking(){const proto=(Phaser.Game as any)?.prototype;if(!proto||proto.__jwV23Tracked)return;const boot=proto.boot,destroy=proto.destroy;if(typeof boot==='function')proto.boot=function(...args:any[]){trackedGames.add(this);return boot.apply(this,args);};if(typeof destroy==='function')proto.destroy=function(...args:any[]){trackedGames.delete(this);return destroy.apply(this,args);};proto.__jwV23Tracked=true;}
installTracking();
function scene():any|null{const games=[...trackedGames,...((((Phaser as any).GAMES||[]) as any[]))];for(const game of games){const direct=game?.scene?.keys?.world;if(direct?.sys?.isActive?.())return direct;try{const s=game?.scene?.getScene?.('world');if(s?.sys?.isActive?.())return s;}catch{}}return null;}
function makeTexture(s:any,key:string,robe:number,accent:number,service:Service){if(s.textures?.exists?.(key))return;const g=s.add.graphics();g.fillStyle(0x0d1717,.26).fillEllipse(28,72,42,9);g.fillStyle(0xe3b18a).fillCircle(28,20,13);g.fillStyle(0x2b241f).fillRoundedRect(15,5,26,13,6);g.fillStyle(robe).fillRoundedRect(12,33,32,33,9);g.fillStyle(accent).fillRoundedRect(24,34,8,30,3);g.fillStyle(0x262b28).fillRect(16,63,10,11).fillRect(31,63,10,11);if(service==='forge'){g.fillStyle(0x8a603d).fillRect(45,31,5,32);g.fillStyle(0xbfc8ce).fillRoundedRect(41,24,13,8,2);g.fillStyle(0xe4ba64).fillCircle(47,27,3);}else if(service==='guide'){g.fillStyle(0xd9e5ef).fillRoundedRect(46,34,11,22,2);g.lineStyle(1,0x6a7890,.8).lineBetween(48,39,55,39).lineBetween(48,44,55,44).lineBetween(48,49,54,49);}else if(service==='trainer'){g.fillStyle(0xb8c4cb).fillTriangle(49,17,55,45,43,45);g.fillStyle(0x5b4028).fillRect(47,44,4,24);g.fillStyle(0xd6ad57).fillRect(42,43,14,4);}else{g.fillStyle(0xe9d1dd).fillCircle(49,38,8);g.fillStyle(0xa85f78).fillRect(47,31,4,14).fillRect(42,36,14,4);}g.lineStyle(2,0x18211e,.82).strokeRoundedRect(12,33,32,33,9);g.generateTexture(key,62,78);g.destroy();}
function createNpc(s:any,def:HubNpc){const key=`jw23-${def.id}`;makeTexture(s,key,def.robe,def.accent,def.service);const shadow=s.add.ellipse(0,35,42,10,0x0c1712,.27);const art=s.add.image(0,0,key);const marker=s.add.text(0,-50,'!',{fontFamily:'Noto Sans KR',fontSize:'16px',fontStyle:'bold',color:'#ffe48a',stroke:'#302510',strokeThickness:4}).setOrigin(.5);const label=s.add.text(0,50,def.name,{fontFamily:'Noto Sans KR',fontSize:'9px',fontStyle:'bold',color:'#fff3d2',stroke:'#101816',strokeThickness:4}).setOrigin(.5);const role=s.add.text(0,61,def.role,{fontFamily:'Noto Sans KR',fontSize:'7px',color:'#b8c7cd',stroke:'#101816',strokeThickness:3}).setOrigin(.5);const c=s.add.container(def.x,def.y,[shadow,art,marker,label,role]).setDepth(def.y+25);c.setData('jw23Def',def);s.tweens.add({targets:marker,y:{from:-51,to:-55},duration:760+Math.round(def.x%170),yoyo:true,repeat:-1,ease:'Sine.inOut'});s.tweens.add({targets:art,y:{from:-1,to:1},duration:1000+Math.round(def.y%240),yoyo:true,repeat:-1,ease:'Sine.inOut'});return c;}
function ensureState(s:any){let st=states.get(s);if(!st){st={npcs:defs.map(d=>createNpc(s,d)),zone:String(s.zone||'village'),nearest:null,marker:null};states.set(s,st);}const village=String(s.zone||'village')==='village';st.npcs.forEach(n=>n.setVisible(village));return st;}
function nearest(s:any,st:HubState,radius=145){if(String(s.zone)!=='village'||!s.player)return null;let best:any=null,dist=radius;for(const n of st.npcs){if(!n.visible)continue;const d=Phaser.Math.Distance.Between(s.player.x,s.player.y,n.x,n.y);if(d<dist){dist=d;best=n;}}return best;}
function serviceLabel(service:Service){return service==='forge'?'제작소 열기':service==='guide'?'가이드북 열기':service==='trainer'?'청운들판 출정':'체력 회복';}
function createUi(){if(!document.querySelector('.jw23-nearby')){const n=document.createElement('div');n.className='jw23-nearby hidden';n.innerHTML='<span id="jw23-near-name">NPC</span><b>E</b><small>대화</small>';document.body.appendChild(n);}if(!document.querySelector('.jw23-talk-button')){const b=document.createElement('button');b.type='button';b.className='jw23-talk-button hidden';b.innerHTML='대화<small>NPC</small>';b.addEventListener('click',()=>interact());document.body.appendChild(b);}if(!document.querySelector('.jw23-panel')){const panel=document.createElement('section');panel.className='jw23-panel hidden';panel.innerHTML='<div class="jw23-panel-head"><div><small id="jw23-role">백운성 주민</small><h3 id="jw23-name">NPC</h3></div><button type="button" id="jw23-close">×</button></div><p id="jw23-intro"></p><div class="jw23-player-summary" id="jw23-summary"></div><button type="button" id="jw23-action" class="jw23-action">이용하기</button>';document.body.appendChild(panel);panel.querySelector('#jw23-close')?.addEventListener('click',()=>panel.classList.add('hidden'));panel.querySelector('#jw23-action')?.addEventListener('click',()=>performService());}}
function maxHp(save:any){const base=save?.heroClass==='mage'?92:save?.heroClass==='ranger'?104:120;let rare=0;for(const key of (Array.isArray(save?.rareItems)?save.rareItems:[])){if(key==='cloudCharm')rare+=20;if(key==='moonRing')rare+=55;}return base+Math.max(0,Number(save?.level||1)-1)*14+Number(save?.armorLevel||0)*16+rare;}
function summary(save:any,service:Service){const lv=Number(save?.level||1),w=Number(save?.weaponLevel||0),a=Number(save?.armorLevel||0),hp=Math.max(0,Math.round(Number(save?.hp||0))),max=maxHp(save);if(service==='forge')return `<span>Lv.${lv}</span><span>무기 +${w}</span><span>방어구 +${a}</span>`;if(service==='guide')return `<span>Lv.${lv}</span><span>퀘스트 ${Number(save?.quest||0)+1}단계</span><span>처치 ${Number(save?.kills||0)}</span>`;if(service==='trainer')return `<span>Lv.${lv}</span><span>청운들판 Lv.1+</span><span>전투 준비</span>`;return `<span>현재 HP ${hp}</span><span>최대 HP ${max}</span><span>${hp>=max?'회복 완료':'치료 가능'}</span>`;}
let activeDef:HubNpc|null=null;
function showPanel(s:any,npc:any){createUi();const def=npc?.getData?.('jw23Def') as HubNpc|undefined;if(!def)return;activeDef=def;const panel=document.querySelector<HTMLElement>('.jw23-panel'),name=document.querySelector<HTMLElement>('#jw23-name'),role=document.querySelector<HTMLElement>('#jw23-role'),intro=document.querySelector<HTMLElement>('#jw23-intro'),sum=document.querySelector<HTMLElement>('#jw23-summary'),action=document.querySelector<HTMLButtonElement>('#jw23-action');if(!panel||!name||!role||!intro||!sum||!action)return;name.textContent=def.name;role.textContent=def.role;intro.textContent=def.intro;sum.innerHTML=summary(s.save||{},def.service);action.textContent=serviceLabel(def.service);panel.classList.remove('hidden');}
function toast(text:string){const host=document.querySelector<HTMLElement>('#toast');if(host){host.textContent=text;host.classList.remove('hidden');window.setTimeout(()=>host.classList.add('hidden'),2200);return;}let el=document.querySelector<HTMLElement>('.jw23-toast');if(!el){el=document.createElement('div');el.className='jw23-toast';document.body.appendChild(el);}el.textContent=text;el.classList.add('show');window.setTimeout(()=>el?.classList.remove('show'),2200);}
function heal(s:any){const save=s?.save;if(!save)return;const max=maxHp(save);save.hp=max;try{localStorage.setItem('junja-world-v01',JSON.stringify(save));}catch{}const p=s.player;if(p){const ring=s.add.circle(p.x,p.y,25,0xf3b9d5,.06).setStrokeStyle(5,0xffd7e7,.92).setDepth(p.y+120);s.tweens.add({targets:ring,scale:3.2,alpha:0,duration:520,onComplete:()=>ring.destroy()});for(let i=0;i<8;i++){const m=s.add.circle(p.x+Phaser.Math.Between(-25,25),p.y+Phaser.Math.Between(-5,25),3,0xffd1e5,.85).setDepth(p.y+125);s.tweens.add({targets:m,y:m.y-55,alpha:0,duration:650+i*25,onComplete:()=>m.destroy()});}}toast('의원 하린의 치료로 체력이 모두 회복되었습니다.');}
function performService(){const s=scene();if(!s||!activeDef)return;document.querySelector<HTMLElement>('.jw23-panel')?.classList.add('hidden');if(activeDef.service==='forge'){document.querySelector<HTMLButtonElement>('#workshop-enter')?.click();return;}if(activeDef.service==='guide'){document.querySelector<HTMLButtonElement>('.jw15-guide-button')?.click();return;}if(activeDef.service==='trainer'){try{s.travel?.('field');toast('수련교관 무영이 청운들판으로 안내합니다.');}catch{document.querySelector<HTMLButtonElement>('[data-zone="field"]')?.click();}return;}heal(s);}
function interact(){const s=scene();if(!s?.player)return;const st=ensureState(s),npc=nearest(s,st);if(npc)showPanel(s,npc);}
function bindKeys(){window.addEventListener('keydown',(e:KeyboardEvent)=>{const t=e.target as HTMLElement|null;if(t?.matches('input,textarea,select,[contenteditable="true"]'))return;if(e.code==='KeyE'){const s=scene(),st=s?states.get(s):null;if(s&&st&&nearest(s,st)){e.preventDefault();window.setTimeout(()=>interact(),0);}}},true);}
function updatePrompt(s:any,st:HubState){const npc=nearest(s,st),prompt=document.querySelector<HTMLElement>('.jw23-nearby'),button=document.querySelector<HTMLElement>('.jw23-talk-button'),name=document.querySelector<HTMLElement>('#jw23-near-name');st.nearest=npc;if(!prompt||!button||!name)return;if(!npc){prompt.classList.add('hidden');button.classList.add('hidden');return;}const def=npc.getData?.('jw23Def') as HubNpc;name.textContent=def?.name||'NPC';prompt.classList.remove('hidden');button.classList.remove('hidden');}
function tick(){createUi();const s=scene();if(!s?.player)return;const st=ensureState(s);st.zone=String(s.zone||'village');updatePrompt(s,st);if(String(s.zone)!=='village')document.querySelector<HTMLElement>('.jw23-panel')?.classList.add('hidden');}
function boot(){createUi();bindKeys();window.setInterval(tick,160);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
